// Tree-sitter external scanner generated by monogram.
//
// COMPLETE — the regex-literal scan and the template-literal scan are both
// wired from the grammar's token hints (`regexContext` and `template`).
//
// All language-specific data below is DERIVED from the CstGrammar, not
// hardcoded: the regex flag chars and the template delimiters all come from
// the grammar's token hints.

#include "tree_sitter/parser.h"
#include "tree_sitter/alloc.h"
#include <string.h>
#include <wctype.h>

enum TokenType {
  NO_EXTERNAL_TOKENS,
};

// The scanner is stateless — tree-sitter's `valid_symbols` already encodes
// the parse context (inside a regex slot? inside a template span?), and the
// `${ … }` brace nesting is handled by the template_substitution rule in the
// CFG, so there is nothing to (de)serialize.
typedef struct { char unused; } Scanner;

void *tree_sitter_yaml_external_scanner_create(void) {
  return ts_calloc(1, sizeof(Scanner));
}

void tree_sitter_yaml_external_scanner_destroy(void *payload) {
  ts_free(payload);
}

unsigned tree_sitter_yaml_external_scanner_serialize(void *payload, char *buffer) {
  (void)payload; (void)buffer;
  return 0;
}

void tree_sitter_yaml_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
  (void)payload; (void)buffer; (void)length;
}

static inline void advance(TSLexer *lexer) { lexer->advance(lexer, false); }
static inline void skip(TSLexer *lexer) { lexer->advance(lexer, true); }

bool tree_sitter_yaml_external_scanner_scan(void *payload, TSLexer *lexer,
                                                          const bool *valid_symbols) {
  (void)payload;

  return false;
}
