// Tree-sitter external scanner generated by monogram (indentation path).
//
// Mirrors the indent-stack state machine of src/gen-lexer.ts: INDENT / DEDENT / NEWLINE are emitted
// from the line-leading column relative to an indent stack; a block-scalar body is scanned verbatim.
// All language data (comment introducer, block-scalar introducers, document markers) is DERIVED from
// the grammar's `indent` config — nothing below is hand-tuned for a specific language.

#include "tree_sitter/parser.h"
#include "tree_sitter/alloc.h"
#include <string.h>

enum TokenType {
  INDENT,
  DEDENT,
  NEWLINE,
  BLOCK_SCALAR,
  PLAIN,
  KEY,
  NUM,
  BOOL_NULL,
};

typedef struct {
  uint32_t len;          // indent-stack depth (>= 1; stack[0] == 0, the document level)
  uint32_t cap;
  int16_t *stack;        // indentation columns
  int16_t pending_col;   // column of the line boundary mid-processing (-1 = none)
  bool pending_newline;  // a NEWLINE is still owed once dedents reach pending_col
  bool started;          // any content lexed yet (suppresses a leading NEWLINE)
} Scanner;

static inline void advance(TSLexer *lexer) { lexer->advance(lexer, false); }
static inline void skip(TSLexer *lexer) { lexer->advance(lexer, true); }

static void push_indent(Scanner *s, int16_t col) {
  if (s->len == s->cap) { s->cap *= 2; s->stack = ts_realloc(s->stack, s->cap * sizeof(int16_t)); }
  s->stack[s->len++] = col;
}

void *tree_sitter_yaml_external_scanner_create(void) {
  Scanner *s = ts_malloc(sizeof(Scanner));
  s->cap = 16; s->len = 1;
  s->stack = ts_malloc(s->cap * sizeof(int16_t));
  s->stack[0] = 0;
  s->pending_col = -1; s->pending_newline = false; s->started = false;
  return s;
}

void tree_sitter_yaml_external_scanner_destroy(void *payload) {
  Scanner *s = (Scanner *)payload;
  ts_free(s->stack);
  ts_free(s);
}

unsigned tree_sitter_yaml_external_scanner_serialize(void *payload, char *buffer) {
  Scanner *s = (Scanner *)payload;
  unsigned n = 0;
  buffer[n++] = s->started ? 1 : 0;
  buffer[n++] = s->pending_newline ? 1 : 0;
  memcpy(&buffer[n], &s->pending_col, sizeof(int16_t)); n += sizeof(int16_t);
  uint32_t count = s->len;
  while (n + sizeof(uint32_t) + count * sizeof(int16_t) > TREE_SITTER_SERIALIZATION_BUFFER_SIZE && count > 0) count--;
  memcpy(&buffer[n], &count, sizeof(uint32_t)); n += sizeof(uint32_t);
  memcpy(&buffer[n], s->stack, count * sizeof(int16_t)); n += count * sizeof(int16_t);
  return n;
}

void tree_sitter_yaml_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
  Scanner *s = (Scanner *)payload;
  s->len = 1; s->stack[0] = 0; s->pending_col = -1; s->pending_newline = false; s->started = false;
  if (length < 2 + sizeof(int16_t) + sizeof(uint32_t)) return;
  unsigned n = 0;
  s->started = buffer[n++] != 0;
  s->pending_newline = buffer[n++] != 0;
  memcpy(&s->pending_col, &buffer[n], sizeof(int16_t)); n += sizeof(int16_t);
  uint32_t count; memcpy(&count, &buffer[n], sizeof(uint32_t)); n += sizeof(uint32_t);
  if (count == 0) return; // keep stack[0] = 0
  while (s->cap < count) { s->cap *= 2; s->stack = ts_realloc(s->stack, s->cap * sizeof(int16_t)); }
  memcpy(s->stack, &buffer[n], count * sizeof(int16_t));
  s->len = count;
}

// A block scalar (`|` / `>`): the introducer + indicators + the verbatim more-indented body, as
// one token. The body runs while a line is blank or indented MORE than the parent block level (the
// stack top); it ends at the first non-blank line at or below the parent, or a column-0 document
// marker, or EOF. mark_end is advanced only over lines that belong to the scalar, so the next node's
// indentation is left for the normal boundary logic.
static bool scan_block_scalar(Scanner *s, TSLexer *lexer) {
  int parent = s->stack[s->len - 1];
  advance(lexer); // the introducer (| or >)
  while (lexer->lookahead == '+' || lexer->lookahead == '-' || (lexer->lookahead >= '0' && lexer->lookahead <= '9')) advance(lexer);
  while (lexer->lookahead != 0 && lexer->lookahead != '\n' && lexer->lookahead != '\r') advance(lexer);
  lexer->mark_end(lexer); // the header line belongs to the scalar
  for (;;) {
    if (lexer->lookahead == '\r') { advance(lexer); if (lexer->lookahead == '\n') advance(lexer); }
    else if (lexer->lookahead == '\n') advance(lexer);
    else break; // EOF
    int col = 0;
    while (lexer->lookahead == ' ') { advance(lexer); col++; }
    int32_t c = lexer->lookahead;
    if (c == 0 || c == '\n' || c == '\r') { lexer->mark_end(lexer); continue; } // blank line → body
    if (col <= parent) break; // dedent to/below parent ends the scalar (the line is the next node)
    while (lexer->lookahead != 0 && lexer->lookahead != '\n' && lexer->lookahead != '\r') advance(lexer);
    lexer->mark_end(lexer);
  }
  lexer->result_symbol = BLOCK_SCALAR;
  return true;
}

// A PLAIN / KEY scalar. A tree-sitter token() DFA can't decide a plain scalar's boundary (a `:` is
// content unless followed by space/EOL/flow-indicator; a `#` starts a comment only after a space),
// so we scan it here where look-ahead IS available. The run starts at the current column and ends
// BEFORE the first key/value `:`-separator, comment, flow indicator, newline, or EOF; trailing
// whitespace is trimmed. KEY vs PLAIN is decided by whether a `:`-separator immediately follows.
//
// A number- or bool/null-SHAPED run is left to the regex `num`/`bool_null` tokens (return false →
// tree-sitter rolls back our advances and the typed token matches) — but ONLY where such a token is
// valid. A multi-line plain fold's continuation line is plain-ONLY (its KEY symbol is not valid), so
// a numeric-looking continuation ("123" under a plain scalar) must stay PLAIN, not be handed to num.
static bool scan_scalar(TSLexer *lexer, bool want_key, bool want_plain, bool want_num, bool want_boolnull) {
  char buf[64];
  unsigned blen = 0;        // run text (capped) — for the number/bool-null shape test
  bool has_content = false;
  bool stopped_at_kv = false; // ended at a `:`-separator → this scalar is a mapping KEY
  for (;;) {
    int32_t c = lexer->lookahead;
    if (c == 0 || c == '\n' || c == '\r') break;                 // newline / EOF
    if (c == ',' || c == '[' || c == ']' || c == '{' || c == '}') break; // flow indicators end a scalar
    if (!has_content && (c == '-' || c == '?')) {
      // A leading `-`/`?` is a block indicator (seq entry / explicit key) when followed by space/EOL/
      // flow-indicator, and scalar content otherwise (`-1`, `?x`). Peek the next char to decide.
      lexer->advance(lexer, false);
      int32_t n = lexer->lookahead;
      if (n == 0 || n == ' ' || n == '\t' || n == '\n' || n == '\r' ||
          n == ',' || n == '[' || n == ']' || n == '{' || n == '}') return false; // indicator, not a scalar
      if (blen < sizeof(buf)) buf[blen++] = (char)c;               // `-`/`?` glued to non-space is content
      has_content = true;
      lexer->mark_end(lexer);
      continue;
    }
    if (c == ':') {
      lexer->advance(lexer, false);                               // past the ':' to peek the next char
      int32_t n = lexer->lookahead;
      if (n == 0 || n == ' ' || n == '\t' || n == '\n' || n == '\r' ||
          n == ',' || n == '[' || n == ']' || n == '{' || n == '}') {
        stopped_at_kv = true; break;                              // ':' is a key/value separator → end before it
      }
      if (blen < sizeof(buf)) buf[blen++] = ':';                  // ':' glued to non-space is content
      has_content = true;
      lexer->mark_end(lexer);
      continue;
    }
    if (c == ' ' || c == '\t') {
      lexer->advance(lexer, false);                               // past the space to peek the next char
      if (lexer->lookahead == '#') break;                        // " #" begins a comment → end before the space
      if (blen < sizeof(buf)) buf[blen++] = ' ';                  // interior space (e.g. "hello world")
      continue;                                                   // do NOT mark_end → trailing spaces are trimmed
    }
    if (blen < sizeof(buf)) buf[blen++] = (char)c;
    has_content = true;
    lexer->advance(lexer, false);
    lexer->mark_end(lexer);                                       // token end follows the last content char
  }
  if (!has_content) return false;

  // Number / bool-null SHAPE test (so the typed regex tokens still classify `1`/`true`). Decide KEY
  // vs PLAIN first, because a typed-looking run is only deferred where a typed token is valid: a KEY
  // position admits num/bool_null (block_key_scalar), and a non-KEY value position likewise — but a
  // plain-ONLY fold continuation (neither KEY here, and the run is not a key) must stay PLAIN.
  // numeric / bool-null SHAPE test — a loose superset is fine for classification (only a typed-shaped
  // run is emitted as NUM/BOOL_NULL; a run with any other char is PLAIN), at the cost of mis-typing a
  // rare plain like `1abc` as numeric (the documented imprecise edge).
  bool numeric = blen > 0;
  for (unsigned i = 0; i < blen; i++) {
    char ch = buf[i];
    bool ok = (ch >= '0' && ch <= '9') || ch == '.' || ch == '+' || ch == '-' || ch == 'e' || ch == 'E' ||
              ch == 'x' || ch == 'o' || ch == 'n' /* inf/nan */ || ch == 'a' || ch == 'f' || ch == 'i' ||
              ch == 'I' || ch == 'N' || ch == 'F' || (ch >= 'A' && ch <= 'F');
    if (!ok) { numeric = false; break; }
  }
  // also require at least one digit OR a .inf/.nan/~ shape so a bare "e"/"a" word isn't called numeric
  if (numeric) {
    bool any_digit = false;
    for (unsigned i = 0; i < blen; i++) if (buf[i] >= '0' && buf[i] <= '9') { any_digit = true; break; }
    if (!any_digit) numeric = false;
  }
  bool boolnull = false;
  {
    static const char *WORDS[] = { "true","True","TRUE","false","False","FALSE","null","Null","NULL","~" };
    for (unsigned w = 0; w < sizeof(WORDS)/sizeof(WORDS[0]); w++) {
      const char *p = WORDS[w]; unsigned i = 0;
      while (i < blen && p[i] && buf[i] == p[i]) i++;
      if (i == blen && p[i] == 0) { boolnull = true; break; }
    }
  }
  // Classify + emit. The external scalar token CARRIES the key-vs-value decision (a trailing `: `
  // means KEY), which the GLR parser needs to chain mapping entries — so a typed value is emitted as
  // NUM/BOOL_NULL here, NOT deferred to a regex token (deferring drops the disambiguation and
  // mis-parses a top-level `x: 1\ny: 2`). A key wins first; then the typed shapes; then PLAIN. Each
  // is gated on its token being admissible here (valid_symbols), falling through otherwise.
  if (stopped_at_kv && want_key) { lexer->result_symbol = KEY; return true; }
  if (numeric && want_num) { lexer->result_symbol = NUM; return true; }
  if (boolnull && want_boolnull) { lexer->result_symbol = BOOL_NULL; return true; }
  if (want_plain) { lexer->result_symbol = PLAIN; return true; }
  if (want_key) { lexer->result_symbol = KEY; return true; }
  return false;
}

bool tree_sitter_yaml_external_scanner_scan(void *payload, TSLexer *lexer, const bool *valid_symbols) {
  Scanner *s = (Scanner *)payload;
  bool want_indent = valid_symbols[INDENT];
  bool want_dedent = valid_symbols[DEDENT];
  bool want_newline = valid_symbols[NEWLINE];
  bool want_block = valid_symbols[BLOCK_SCALAR];

  // Finish a line boundary already in progress: emit the remaining DEDENTs (one per call), then the
  // owed NEWLINE when the stack top reaches the boundary column. No input is consumed here.
  if (s->pending_col >= 0) {
    int top = s->stack[s->len - 1];
    if (s->pending_col < top) {
      if (want_dedent) { s->len--; lexer->result_symbol = DEDENT; return true; }
      s->pending_col = -1; s->pending_newline = false; return false;
    }
    bool owed = s->pending_newline;
    int16_t col = s->pending_col;
    s->pending_col = -1; s->pending_newline = false;
    if (col == top && owed && want_newline && s->started) { lexer->result_symbol = NEWLINE; return true; }
    return false;
  }

  // A block scalar value (`key: |`): scan its body before the indent logic — its more-indented
  // lines are content, not nested structure. Skip the inline space after the `:`/`-` first.
  if (want_block) {
    while (lexer->lookahead == ' ' || lexer->lookahead == '\t') skip(lexer);
    if (lexer->lookahead == '|' || lexer->lookahead == '>') { if (scan_block_scalar(s, lexer)) return true; }
  }

  // A SCALAR (plain / key / num / bool-null) on the CURRENT line — NOT at a line boundary (a leading
  // newline falls through to the indent logic so INDENT/DEDENT/NEWLINE are emitted first). Skip inline
  // spaces/tabs, then if the next char could begin a plain scalar (not a newline/EOF and not a YAML
  // indicator — a leading `-`/`?`/`:` is resolved inside scan_scalar), scan it where look-ahead is
  // available. scan_scalar classifies the run and emits the admissible token.
  if (valid_symbols[PLAIN] || valid_symbols[KEY] || valid_symbols[NUM] || valid_symbols[BOOL_NULL]) {
    while (lexer->lookahead == ' ' || lexer->lookahead == '\t') skip(lexer);
    int32_t h = lexer->lookahead;
    bool indicator = h == 0 || h == '\n' || h == '\r' || h == ',' || h == '[' || h == ']' || h == '{' ||
                     h == '}' || h == '#' || h == '&' || h == '*' || h == '!' || h == '|' || h == '>' ||
                     h == '\'' || h == '"' || h == '%' || h == '@' || h == '`';
    if (!indicator) {
      if (scan_scalar(lexer, valid_symbols[KEY] != 0, valid_symbols[PLAIN] != 0, valid_symbols[NUM] != 0, valid_symbols[BOOL_NULL] != 0)) { s->started = true; return true; }
    }
  }

  if (!want_indent && !want_dedent && !want_newline) return false; // flow context — no indent tokens valid

  // Skip blank lines, comment-only lines, and leading whitespace, noting whether a line break was
  // crossed (only a real boundary drives the indent logic).
  bool found_eol = false;
  for (;;) {
    int32_t c = lexer->lookahead;
    if (c == '\n') { skip(lexer); found_eol = true; }
    else if (c == '\r') { skip(lexer); if (lexer->lookahead == '\n') skip(lexer); found_eol = true; }
    else if (c == ' ' || c == '\t') { skip(lexer); }
    else if (c == '#') { while (lexer->lookahead != 0 && lexer->lookahead != '\n' && lexer->lookahead != '\r') skip(lexer); }
    else break; // content or EOF
  }

  if (lexer->eof(lexer)) {
    if (s->len > 1 && want_dedent) { s->len--; lexer->result_symbol = DEDENT; return true; } // close open blocks at EOF
    return false;
  }
  bool was_started = s->started;
  s->started = true; // content lies ahead — mark started even on a mid-line return
  if (!found_eol) return false; // not at a line boundary

  int16_t col = (int16_t)lexer->get_column(lexer);
  lexer->mark_end(lexer); // INDENT/DEDENT/NEWLINE are zero-width at the content column
  int top = s->stack[s->len - 1];

  if (col > top) {
    if (want_indent) { push_indent(s, col); lexer->result_symbol = INDENT; return true; }
    return false;
  }
  if (col == top) {
    if (want_newline && was_started) { lexer->result_symbol = NEWLINE; return true; }
    return false;
  }
  // col < top: a dedent. Emit one DEDENT now; queue the rest + the trailing NEWLINE for re-entry.
  if (want_dedent) {
    s->pending_col = col; s->pending_newline = true;
    s->len--; lexer->result_symbol = DEDENT; return true;
  }
  return false;
}
