// curated-corpora.ts — small hand-written corpora shared by the folded scope-gap / src-coverage drivers.
// JSX (plain-JS + JSX halves) and realistic HTML — the languages with no public single-file corpus.

export const JSX_CASES: string[] = [
  // --- plain JS half ---
  'const x = 1, y = 2;',
  'function f(a, b = 1, ...rest) { return a + b + rest.length; }',
  'class C extends B { #p = 1; static s() {} get v() { return this.#p; } }',
  'const g = async (x) => { for await (const v of x) console.log(v); };',
  'const { a, b: { c } = {}, ...r } = obj;',
  'label: for (let i = 0; i < 10; i++) { if (i) continue label; }',
  'try { risky(); } catch { recover(); } finally { done(); }',
  'a ??= b; c ||= d; e &&= f; g?.h?.[i]?.(j);',
  'const t = `a${b}c${d}e`, n = 1_000_000n, hex = 0xFF, oct = 0o17, bin = 0b101;',
  'export default function () {}; export const z = 1; export * from "m";',
  'import def, { named as alias } from "mod"; import * as ns from "ns";',
  'switch (x) { case 1: break; default: { let y = 2; } }',
  'do { step(); } while (cond);',
  'const re = /foo\\d+/giu; const s = "a\\u{1F600}b";',
  'new.target; import.meta.url; function* gen() { yield* other(); }',
  // --- JSX half ---
  'const a = <div />;',
  'const b = <div className="x" id={y} data-z={1} {...props}>text</div>;',
  'const frag = <><Alpha /><Beta /></>;',
  'const member = <Foo.Bar.Baz prop={1} />;',
  'const ns = <svg:rect width="10" />;',
  'const nested = <Outer header={<Inner title="x" />}>{children}</Outer>;',
  'const cond = ok ? <Yes /> : <No />;',
  'const list = items.map((it) => <li key={it.id}>{it.label}</li>);',
  'const guard = <div>{show && <Modal />}{count || <Empty />}</div>;',
  'const text = <p> leading {a} middle {b} trailing </p>;',
  'const selfClosingVoid = <input type="text" disabled />;',
  'const entity = <span>a &amp; b &lt; c &#x1F600;</span>;',
  'const multiline = (\n  <section>\n    <h1>Title</h1>\n    <p>Body</p>\n  </section>\n);',
  'const exprChild = <div>{/* comment */}{items.length}</div>;',
  'const spreadChild = <List>{...rows}</List>;',
  'function App() { return <main><Header /><Content /></main>; }',
  'const attrExpr = <a href={"/" + slug} onClick={() => go()}>link</a>;',
  'const deep = <a><b><c>deep</c></b></a>;',
  'const stringAttr = <div title=\'single\' alt="double" />;',
  'const boolAttr = <button autofocus formNoValidate>ok</button>;',
];

export const HTML_GENERAL: string[] = [
  '<div class="container" id="main"><p>Hello <a href="/x">world</a>.</p></div>',
  '<ul><li>one</li><li>two</li><li>three</li></ul>',
  '<img src="a.png" alt="a picture" width="100" height="80">',
  '<input type="text" name="q" placeholder="Search" disabled>',
  '<button type="submit" class="btn btn-primary" data-id="42">Go</button>',
  '<section><h1>Title</h1><p>Body with <strong>bold</strong> and <em>italic</em>.</p></section>',
  '<nav><a href="/">Home</a> | <a href="/about">About</a></nav>',
  '<form action="/submit" method="post"><label for="n">Name</label><input id="n"></form>',
  '<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>1</td><td>2</td></tr></tbody></table>',
  '<!-- a comment --><div><!-- inline --><span>x</span></div>',
  '<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">',
  '<br><hr>',
  '<select><option value="1">One</option><option value="2" selected>Two</option></select>',
  '<video controls width="320"><source src="m.mp4" type="video/mp4"></video>',
  '<article data-index=3 hidden><header>H</header><footer>F</footer></article>',
  '<span class="a b c" title="x y z">text</span>',
  '<div\n  class="multi-line"\n  id="tag"\n  data-x="1">body</div>',
  '<a href="https://example.com?a=1&b=2" target="_blank" rel="noopener">link</a>',
  '<label>Email <input type="email" required></label>',
  '<figure><img src="p.jpg" alt="photo"><figcaption>cap</figcaption></figure>',
];
