// ─────────────────────────────────────────────────────────────────────────────
//  html-highlight.ts — gates the DERIVED HTML TextMate grammar (html.tmLanguage.json,
//  generated by gen-tm's markup path). Tokenizes HTML with vscode-textmate (the real
//  VS Code engine) and asserts the scopes themes key on: tag name, tag punctuation,
//  attribute name / value, comment, and — the markup payoff — that raw-text element
//  bodies (`<script>1 < 2</script>`) are an embedded region, NOT mis-scoped as tags.
//
//  Raw-text regions embed `source.js` / `source.css`. vscode-textmate DROPS a begin/end
//  rule whose patterns reference an unregistered grammar, so the test registers small
//  stubs for those scopes (a `[^<]+` matcher that stops at `<`, letting the region's
//  close tag fire). In a real editor the actual JS/CSS grammars fill that role.
//
//  Run: node test/html-highlight.ts
// ─────────────────────────────────────────────────────────────────────────────
import vsctm from 'vscode-textmate';
import onig from 'vscode-oniguruma';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const { INITIAL, Registry, parseRawGrammar } = vsctm;
const require = createRequire(import.meta.url);
const wasmBin = readFileSync(require.resolve('vscode-oniguruma/release/onig.wasm'));
await onig.loadWASM(wasmBin.buffer.slice(wasmBin.byteOffset, wasmBin.byteOffset + wasmBin.byteLength));

const grammarJson = readFileSync('html.tmLanguage.json', 'utf-8');
const embedStub = (scope: string) =>
  JSON.stringify({ scopeName: scope, patterns: [{ match: '[^<]+', name: `${scope}.embedded` }] });

const registry = new Registry({
  onigLib: Promise.resolve({
    createOnigScanner: (p: string[]) => new onig.OnigScanner(p),
    createOnigString: (s: string) => new onig.OnigString(s),
  }),
  loadGrammar: async (sn: string) => {
    if (sn === 'text.html.basic') return parseRawGrammar(grammarJson, 'html.tmLanguage.json');
    if (sn === 'source.js' || sn === 'source.css') return parseRawGrammar(embedStub(sn), sn + '.json');
    return null;
  },
});
const grammar = (await registry.loadGrammar('text.html.basic'))!;

interface Tok { text: string; scopes: string }
function toks(line: string): Tok[] {
  const r = grammar.tokenizeLine(line, INITIAL);
  return r.tokens.map(t => ({ text: line.slice(t.startIndex, t.endIndex), scopes: t.scopes.join(' ') }));
}

let pass = 0, fail = 0;
function expect(line: string, text: string, scope: string) {
  const t = toks(line).find(t => t.text === text);
  if (t && t.scopes.includes(scope)) { pass++; return; }
  fail++;
  console.log(`✗ ${JSON.stringify(line)}\n    token ${JSON.stringify(text)} expected scope ⊇ ${JSON.stringify(scope)}, got: ${t ? t.scopes : '(token not found)'}`);
}
function expectNot(line: string, text: string, scope: string) {
  const bad = toks(line).filter(t => t.text === text && t.scopes.includes(scope));
  if (bad.length === 0) { pass++; return; }
  fail++;
  console.log(`✗ ${JSON.stringify(line)}\n    token ${JSON.stringify(text)} must NOT carry ${JSON.stringify(scope)}, got: ${bad[0].scopes}`);
}

// ── tag name + punctuation ──
expect('<div></div>', 'div', 'entity.name.tag');
expect('<div></div>', '<', 'punctuation.definition.tag');
expect('<div></div>', '>', 'punctuation.definition.tag');
expect('<br/>', 'br', 'entity.name.tag');
expect('<br/>', '/', 'punctuation.definition.tag');
expect('<custom-element>x</custom-element>', 'custom-element', 'entity.name.tag');

// ── attributes (string regions split into delimiter / content / delimiter) ──
expect('<div class="x">hi</div>', 'class', 'entity.other.attribute-name');
expect('<div class="x">hi</div>', '=', 'punctuation.separator.key-value');
expect('<div class="x">hi</div>', 'x', 'string.quoted.double');         // value content
expect('<div class="x">hi</div>', '"', 'punctuation.definition.string'); // value delimiter
expect("<a href='/y'>", '/y', 'string.quoted.single');
expect('<input type="text" disabled>', 'disabled', 'entity.other.attribute-name');
expect('<td colspan=2>', '2', 'string.unquoted');

// ── text content is the (unscoped) root, not a tag ──
expectNot('<p>hello</p>', 'hello', 'entity.name.tag');

// ── comment ──
expect('<!-- a comment -->', '<!--', 'comment.block');
expectNot('<!-- a < b -->', '<', 'punctuation.definition.tag');   // `<` inside a comment is not a tag

// ── raw-text payoff: <script> body is an embedded region, `<`/`>` inside are NOT tags ──
{
  const line = '<script>var a = 1 < 2;</script>';
  const ts = toks(line);
  expect(line, 'script', 'entity.name.tag');
  if (ts.some(t => t.scopes.includes('meta.script'))) pass++;
  else { fail++; console.log('✗ raw-text: <script> did not open a meta.script region'); }
  // every `<` that is script CONTENT (inside the region) must be embedded, never a tag
  const contentLts = ts.filter(t => t.text === '<' && t.scopes.includes('source.js'));
  if (contentLts.length >= 1 && contentLts.every(t => !t.scopes.includes('punctuation.definition.tag'))) pass++;
  else { fail++; console.log(`✗ raw-text: a \`<\` inside <script> was treated as a tag: ${ts.filter(t => t.text === '<').map(t => t.scopes).join(' | ')}`); }
}
// <style> body is an embedded CSS region — the CSS `>` child combinator stays content
{
  const ts = toks('<style>a > b{}</style>');
  expect('<style>a > b{}</style>', 'style', 'entity.name.tag');
  if (ts.some(t => t.scopes.includes('meta.style') && t.scopes.includes('source.css'))) pass++;
  else { fail++; console.log(`✗ <style> body not an embedded source.css region: ${ts.map(t => t.scopes).join(' | ')}`); }
}

console.log(`\nhtml-highlight: ${pass}/${pass + fail} scope checks pass`);
if (fail > 0) { console.log('✗ HTML highlighter FAILED'); process.exit(1); }
console.log('✓ HTML highlighter: tags, attributes, comments, and raw-text regions all scoped correctly');
