// ─────────────────────────────────────────────────────────────────────────────
//  html-monarch.ts — gates the DERIVED Monaco Monarch tokenizer (html.monarch.json,
//  generated by gen-monarch's markup path). Monaco isn't easily run headless, so this
//  embeds a small but faithful interpreter for the Monarch rule subset gen-monarch
//  emits — `[regex, action]` / `[regex, action, next]`, action = token | {token,next,
//  switchTo} — with a persistent state stack (so raw-text / comment bodies span lines).
//  It then asserts the tokens, including the payoff: a `<` inside <script> / <!-- -->
//  is content, never a tag delimiter.
//
//  Run: node test/html-monarch.ts
// ─────────────────────────────────────────────────────────────────────────────
import { readFileSync } from 'node:fs';
import type { MonarchLanguage, MonarchRule } from '../src/gen-monarch.ts';

const mon: MonarchLanguage = JSON.parse(readFileSync('html.monarch.json', 'utf-8'));

interface Tok { text: string; token: string }

// Tokenize `src` (possibly multi-line) the way Monaco's Monarch engine does: per line,
// match the current state's rules in order (anchored at the cursor), emit a token for
// the match, then apply the state transition. The state stack persists across lines.
function tokenize(src: string): Tok[] {
  const out: Tok[] = [];
  const stack: string[] = ['root'];
  for (const line of src.split('\n')) {
    let pos = 0;
    let guard = 0;
    while (pos <= line.length) {
      if (++guard > 10000) throw new Error('Monarch interpreter runaway (no progress)');
      const state = stack[stack.length - 1];
      const rules = (mon.tokenizer[state] ?? []).filter(Array.isArray) as Extract<MonarchRule, unknown[]>[];
      let matched = false;
      for (const rule of rules) {
        const [reSrc, action, third] = rule as [string, any, string?];
        const re = new RegExp('^(?:' + reSrc + ')');
        const m = re.exec(line.slice(pos));
        if (!m) continue;
        const text = m[0];
        const token = typeof action === 'string' ? action : action.token;
        if (text.length > 0) out.push({ text, token });
        // transition: object.next / object.switchTo, or the 3rd tuple element (a push/pop).
        const next = (typeof action === 'object' && (action.next ?? action.switchTo)) || third;
        const isSwitch = typeof action === 'object' && !!action.switchTo;
        if (next === '@pop') stack.pop();
        else if (next === '@popall') stack.splice(1);
        else if (typeof next === 'string' && next.startsWith('@')) {
          const target = next.slice(1);
          if (isSwitch) stack[stack.length - 1] = target;
          else stack.push(target);
        }
        pos += text.length;
        matched = true;
        if (text.length === 0 && !next) { pos++; }   // never stall on a zero-width no-op
        break;
      }
      if (!matched) { pos++; }                         // unmatched char → skip (defaultToken)
      if (pos > line.length) break;
    }
  }
  return out;
}

let pass = 0, fail = 0;
const has = (toks: Tok[], text: string, token: string) => toks.some(t => t.text === text && t.token === token);
function expect(line: string, text: string, token: string) {
  const toks = tokenize(line);
  if (has(toks, text, token)) { pass++; return; }
  fail++;
  console.log(`✗ ${JSON.stringify(line)}\n    expected ${JSON.stringify(text)} → ${token}; got: ${toks.map(t => `${JSON.stringify(t.text)}:${t.token}`).join(' ')}`);
}
function expectNoneAs(line: string, text: string, token: string) {
  const toks = tokenize(line);
  const bad = toks.filter(t => t.text === text && t.token === token);
  if (bad.length === 0) { pass++; return; }
  fail++;
  console.log(`✗ ${JSON.stringify(line)}\n    ${JSON.stringify(text)} must NOT be ${token}`);
}

// ── tags + attributes ──
expect('<div class="x">hi</div>', '<', 'delimiter');
expect('<div class="x">hi</div>', 'div', 'tag');
expect('<div class="x">hi</div>', 'class', 'attribute.name');
expect('<div class="x">hi</div>', '=', 'delimiter');
expect('<div class="x">hi</div>', 'x', 'string');
expect('<div class="x">hi</div>', 'hi', '');            // text content is the uncoloured root
expect('<br/>', 'br', 'tag');
expect('<br/>', '/>', 'delimiter');
expect('<a href="/y">', '/y', 'string');

// ── comment: `<` inside is content, not a delimiter ──
expect('<!-- a < b -->', '<!--', 'comment');
expectNoneAs('<!-- a < b -->', '<', 'delimiter');

// ── raw-text payoff: <script> body is source.js; the inner `<` is NOT a delimiter ──
{
  const line = '<script>var a = 1 < 2;</script>';
  expect(line, 'script', 'tag');
  expect(line, '<', 'source.js');           // the `< 2` angle bracket is JS content (NOT a tag delimiter)
}
// <style> body is source.css
expect('<style>a > b{}</style>', 'a > b{}', 'source.css');

console.log(`\nhtml-monarch: ${pass}/${pass + fail} token checks pass`);
if (fail > 0) { console.log('✗ HTML Monarch tokenizer FAILED'); process.exit(1); }
console.log('✓ HTML Monarch tokenizer: tags, attributes, comments, and raw-text bodies all tokenized correctly');
