;; -----------------------------------------------------------------
;; Tree-sitter highlight queries generated by monogram.
;; Capture names follow the standard tree-sitter highlight vocabulary
;; (@keyword, @function, @type, @string, @property, @operator, …).
;; Inferred from rule SHAPES + the grammar's `scopes` section — the same
;; structural inference the TextMate generator uses.
;; -----------------------------------------------------------------

;; Literal token nodes.
(doc_start) @punctuation.delimiter
(doc_end) @punctuation.delimiter
(directive) @keyword
(comment) @comment
(dquote) @string
(squote) @string
(anchor) @type
(alias) @variable
(tag) @keyword
(block_scalar) @string
(plain) @string

;; Keyword, operator, and punctuation literals.
[
  ":" "?" "-" "{" "," "}" "[" "]"
] @punctuation.delimiter
