// AUTO-GENERATED by src/gen-ast-types.ts — do not edit by hand.
// Typed CST for the parser output of this grammar.
//
// LIMITATION — no named fields: the grammar carries no labels on rule
// elements (e.g. `[$, '.', Ident]` has no field names), so children are
// typed by *kind* (which Node rules / leaf token types can appear), not as
// named accessors like `node.name`/`node.value`. Named-field accessors would
// require adding field labels to the grammar DSL (a future enrichment).

export interface CstPos {
  offset: number;
  end: number;
}

/** Every `tokenType` a CstLeaf in this grammar can carry. */
export type TokenType =
  | 'AttrValue'
  | 'Comment'
  | 'Name'
  | 'RawText'
  | 'Text'
  | 'UnquotedValue'
  | 'VoidName'
  | '$keyword'
  | '$punct'
  | '$operator'
  | '$templateHead'
  | '$templateMiddle'
  | '$templateTail';

/** A terminal: one lexer token (or synthetic keyword/punct/operator leaf). */
export interface CstLeaf extends CstPos {
  kind: 'leaf';
  tokenType: TokenType;
  text: string;
}

/** `Element` node. Children (flattened, in source order) are drawn from: */
export interface ElementNode extends CstPos {
  kind: 'node';
  rule: 'Element';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Name' })
    | (CstLeaf & { tokenType: 'RawText' })
    | (CstLeaf & { tokenType: 'VoidName' })
    | AttrNode
    | NodeNode
  >;
}

/** `Attr` node. Children (flattened, in source order) are drawn from: */
export interface AttrNode extends CstPos {
  kind: 'node';
  rule: 'Attr';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'AttrValue' })
    | (CstLeaf & { tokenType: 'Name' })
    | (CstLeaf & { tokenType: 'UnquotedValue' })
  >;
}

/** `Node` node. Children (flattened, in source order) are drawn from: */
export interface NodeNode extends CstPos {
  kind: 'node';
  rule: 'Node';
  children: Array<
    | (CstLeaf & { tokenType: 'Comment' })
    | (CstLeaf & { tokenType: 'RawText' })
    | (CstLeaf & { tokenType: 'Text' })
    | ElementNode
  >;
}

/** `Document` node. Children (flattened, in source order) are drawn from: */
export interface DocumentNode extends CstPos {
  kind: 'node';
  rule: 'Document';
  children: Array<
    | (CstLeaf & { tokenType: 'Comment' })
    | (CstLeaf & { tokenType: 'Text' })
    | ElementNode
  >;
}

/** Discriminated union of every node kind. Switch on `node.rule` for exhaustiveness. */
export type CstNode =
  | ElementNode
  | AttrNode
  | NodeNode
  | DocumentNode;

/** Every `rule` discriminant value (the keys of the CstNode union). */
export type RuleName =
  | 'Element'
  | 'Attr'
  | 'Node'
  | 'Document';

/** Any CST element: a node or a leaf. */
export type CstChild = CstNode | CstLeaf;

/** Narrow the CstNode union to the node for a given rule name. */
export type NodeOf<R extends RuleName> = Extract<CstNode, { rule: R }>;
