// GENERATED by src/gen-cst-match.ts — do not edit. Per-arm CST destructurers for "html".
/* eslint-disable */
import type { AttrNode, CstChild, CstLeaf, DocumentNode, ElementNode, NodeNode } from "./html.cst-types.ts";

const __lit = (c: readonly CstChild[], i: number, src: string, text: string, tt: string): boolean => {
  const k = c[i] as CstLeaf | undefined;
  return k !== undefined && k.tokenType === tt && k.end - k.offset === text.length && src.startsWith(text, k.offset);
};
const __tok = (c: readonly CstChild[], i: number, name: string): boolean => {
  const k = c[i] as CstLeaf | undefined;
  return k !== undefined && k.tokenType === name;
};
const __nodeOf = (c: readonly CstChild[], i: number, rule: string): boolean => {
  const k = c[i] as { rule?: string } | undefined;
  return k !== undefined && k.rule === rule;
};

export type ElementMatch =
  | { arm: "lt"; voidName: CstLeaf; attr: (AttrNode)[] }
  | { arm: "lt2"; name: CstLeaf; attr: (AttrNode)[] }
  | { arm: "lt3"; name: CstLeaf; attr: (AttrNode)[]; node: (NodeNode)[]; name2: CstLeaf }
  | { arm: "lt4"; name: CstLeaf; attr: (AttrNode)[]; rawText: CstLeaf };

function _Element$lt(c: readonly CstChild[], src: string): ElementMatch | null {
  let voidName: (CstLeaf) | undefined;
  const attr: (AttrNode)[] = [];
  let i = 0;
  if (!__lit(c, i, src, "<", "$punct")) return null;
  i++;
  if (!(__tok(c, i, "VoidName"))) return null;
  voidName = c[i] as CstLeaf;
  i++;
  for (;;) {
    const _t0 = i; let _t1 = true;
    _b2: {
      if (!__nodeOf(c, i, "Attr")) { _t1 = false; break _b2; }
      attr.push(c[i] as AttrNode);
      i++;
    }
    if (!_t1) { i = _t0; break; }
    if (i === _t0) break;
  }
  {
    const _t3 = i; let _t4 = true;
    _b5: {
      if (!__lit(c, i, src, "/", "$punct")) { _t4 = false; break _b5; }
      i++;
    }
    if (!_t4) i = _t3;
  }
  if (!__lit(c, i, src, ">", "$punct")) return null;
  i++;
  if (i !== c.length) return null;
  return { arm: "lt", voidName: voidName!, attr };
}

function _Element$lt2(c: readonly CstChild[], src: string): ElementMatch | null {
  let name: (CstLeaf) | undefined;
  const attr: (AttrNode)[] = [];
  let i = 0;
  if (!__lit(c, i, src, "<", "$punct")) return null;
  i++;
  if (!(__tok(c, i, "Name"))) return null;
  name = c[i] as CstLeaf;
  i++;
  for (;;) {
    const _t0 = i; let _t1 = true;
    _b2: {
      if (!__nodeOf(c, i, "Attr")) { _t1 = false; break _b2; }
      attr.push(c[i] as AttrNode);
      i++;
    }
    if (!_t1) { i = _t0; break; }
    if (i === _t0) break;
  }
  if (!__lit(c, i, src, "/", "$punct")) return null;
  i++;
  if (!__lit(c, i, src, ">", "$punct")) return null;
  i++;
  if (i !== c.length) return null;
  return { arm: "lt2", name: name!, attr };
}

function _Element$lt3(c: readonly CstChild[], src: string): ElementMatch | null {
  let name: (CstLeaf) | undefined;
  const attr: (AttrNode)[] = [];
  const node: (NodeNode)[] = [];
  let name2: (CstLeaf) | undefined;
  let i = 0;
  if (!__lit(c, i, src, "<", "$punct")) return null;
  i++;
  if (!(__tok(c, i, "Name"))) return null;
  name = c[i] as CstLeaf;
  i++;
  for (;;) {
    const _t0 = i; let _t1 = true;
    _b2: {
      if (!__nodeOf(c, i, "Attr")) { _t1 = false; break _b2; }
      attr.push(c[i] as AttrNode);
      i++;
    }
    if (!_t1) { i = _t0; break; }
    if (i === _t0) break;
  }
  if (!__lit(c, i, src, ">", "$punct")) return null;
  i++;
  for (;;) {
    const _t3 = i; let _t4 = true;
    _b5: {
      if (!__nodeOf(c, i, "Node")) { _t4 = false; break _b5; }
      node.push(c[i] as NodeNode);
      i++;
    }
    if (!_t4) { i = _t3; break; }
    if (i === _t3) break;
  }
  if (!__lit(c, i, src, "<", "$punct")) return null;
  i++;
  if (!__lit(c, i, src, "/", "$punct")) return null;
  i++;
  if (!(__tok(c, i, "Name"))) return null;
  name2 = c[i] as CstLeaf;
  i++;
  if (!__lit(c, i, src, ">", "$punct")) return null;
  i++;
  if (i !== c.length) return null;
  return { arm: "lt3", name: name!, attr, node, name2: name2! };
}

function _Element$lt4(c: readonly CstChild[], src: string): ElementMatch | null {
  let name: (CstLeaf) | undefined;
  const attr: (AttrNode)[] = [];
  let rawText: (CstLeaf) | undefined;
  let i = 0;
  if (!__lit(c, i, src, "<", "$punct")) return null;
  i++;
  if (!(__tok(c, i, "Name"))) return null;
  name = c[i] as CstLeaf;
  i++;
  for (;;) {
    const _t0 = i; let _t1 = true;
    _b2: {
      if (!__nodeOf(c, i, "Attr")) { _t1 = false; break _b2; }
      attr.push(c[i] as AttrNode);
      i++;
    }
    if (!_t1) { i = _t0; break; }
    if (i === _t0) break;
  }
  if (!__lit(c, i, src, ">", "$punct")) return null;
  i++;
  if (!(__tok(c, i, "RawText"))) return null;
  rawText = c[i] as CstLeaf;
  i++;
  if (i !== c.length) return null;
  return { arm: "lt4", name: name!, attr, rawText: rawText! };
}

export function matchElement(n: ElementNode, src: string): ElementMatch {
  const c = n.children;
  const k0 = c[0] as (CstChild & { tokenType?: string; rule?: string }) | undefined;
  if (k0 === undefined) {
  } else if (k0.tokenType === undefined) {
    switch (k0.rule) {
    }
  } else if (k0.tokenType === '$keyword' || k0.tokenType === '$punct') {
    switch (src.charCodeAt(k0.offset)) {
      case 60: {
        { const m = _Element$lt(c, src); if (m !== null) return m; }
        { const m = _Element$lt2(c, src); if (m !== null) return m; }
        { const m = _Element$lt3(c, src); if (m !== null) return m; }
        { const m = _Element$lt4(c, src); if (m !== null) return m; }
        break;
      }
    }
  } else {
    switch (k0.tokenType) {
    }
  }
  throw new Error("matchElement: no arm matches" + ' @' + n.offset);
}

export type AttrMatch =
  | { arm: "name"; name: CstLeaf; alt?: { branch: "attrValue"; attrValue: CstLeaf } | { branch: "name"; name: CstLeaf } | { branch: "unquotedValue"; unquotedValue: CstLeaf } };

function _Attr$name(c: readonly CstChild[], src: string): AttrMatch | null {
  let name: (CstLeaf) | undefined;
  let alt: ({ branch: "attrValue"; attrValue: CstLeaf } | { branch: "name"; name: CstLeaf } | { branch: "unquotedValue"; unquotedValue: CstLeaf }) | undefined;
  let i = 0;
  if (!(__tok(c, i, "Name"))) return null;
  name = c[i] as CstLeaf;
  i++;
  {
    const _t0 = i; let _t1 = true;
    _b2: {
      if (!__lit(c, i, src, "=", "$punct")) { _t1 = false; break _b2; }
      i++;
      {
        let _t3 = false;
        if (!_t3) {
          let _t7_attrValue: (CstLeaf) | undefined;
          const _t4 = i; let _t5 = true;
          _b6: {
            if (!(__tok(c, i, "AttrValue"))) { _t5 = false; break _b6; }
            _t7_attrValue = c[i] as CstLeaf;
            i++;
          }
          if (_t5) { _t3 = true; alt = ({ branch: "attrValue", attrValue: _t7_attrValue! }) as typeof alt; }
          else i = _t4;
        }
        if (!_t3) {
          let _t11_name: (CstLeaf) | undefined;
          const _t8 = i; let _t9 = true;
          _b10: {
            if (!(__tok(c, i, "Name"))) { _t9 = false; break _b10; }
            _t11_name = c[i] as CstLeaf;
            i++;
          }
          if (_t9) { _t3 = true; alt = ({ branch: "name", name: _t11_name! }) as typeof alt; }
          else i = _t8;
        }
        if (!_t3) {
          let _t15_unquotedValue: (CstLeaf) | undefined;
          const _t12 = i; let _t13 = true;
          _b14: {
            if (!(__tok(c, i, "UnquotedValue"))) { _t13 = false; break _b14; }
            _t15_unquotedValue = c[i] as CstLeaf;
            i++;
          }
          if (_t13) { _t3 = true; alt = ({ branch: "unquotedValue", unquotedValue: _t15_unquotedValue! }) as typeof alt; }
          else i = _t12;
        }
        if (!_t3) { _t1 = false; break _b2; }
      }
    }
    if (!_t1) i = _t0;
  }
  if (i !== c.length) return null;
  return { arm: "name", name: name!, alt };
}

export function matchAttr(n: AttrNode, src: string): AttrMatch {
  const c = n.children;
  const k0 = c[0] as (CstChild & { tokenType?: string; rule?: string }) | undefined;
  if (k0 === undefined) {
  } else if (k0.tokenType === undefined) {
    switch (k0.rule) {
    }
  } else if (k0.tokenType === '$keyword' || k0.tokenType === '$punct') {
    switch (src.charCodeAt(k0.offset)) {
    }
  } else {
    switch (k0.tokenType) {
      case "Name": {
        { const m = _Attr$name(c, src); if (m !== null) return m; }
        break;
      }
    }
  }
  throw new Error("matchAttr: no arm matches" + ' @' + n.offset);
}

export type NodeMatch =
  | { arm: "element"; element: ElementNode }
  | { arm: "comment"; comment: CstLeaf }
  | { arm: "rawText"; rawText: CstLeaf }
  | { arm: "text"; text: CstLeaf };

function _Node$element(c: readonly CstChild[], src: string): NodeMatch | null {
  let element: (ElementNode) | undefined;
  let i = 0;
  if (!__nodeOf(c, i, "Element")) return null;
  element = c[i] as ElementNode;
  i++;
  if (i !== c.length) return null;
  return { arm: "element", element: element! };
}

function _Node$comment(c: readonly CstChild[], src: string): NodeMatch | null {
  let comment: (CstLeaf) | undefined;
  let i = 0;
  if (!(__tok(c, i, "Comment"))) return null;
  comment = c[i] as CstLeaf;
  i++;
  if (i !== c.length) return null;
  return { arm: "comment", comment: comment! };
}

function _Node$rawText(c: readonly CstChild[], src: string): NodeMatch | null {
  let rawText: (CstLeaf) | undefined;
  let i = 0;
  if (!(__tok(c, i, "RawText"))) return null;
  rawText = c[i] as CstLeaf;
  i++;
  if (i !== c.length) return null;
  return { arm: "rawText", rawText: rawText! };
}

function _Node$text(c: readonly CstChild[], src: string): NodeMatch | null {
  let text: (CstLeaf) | undefined;
  let i = 0;
  if (!(__tok(c, i, "Text"))) return null;
  text = c[i] as CstLeaf;
  i++;
  if (i !== c.length) return null;
  return { arm: "text", text: text! };
}

export function matchNode(n: NodeNode, src: string): NodeMatch {
  const c = n.children;
  const k0 = c[0] as (CstChild & { tokenType?: string; rule?: string }) | undefined;
  if (k0 === undefined) {
  } else if (k0.tokenType === undefined) {
    switch (k0.rule) {
      case "Element": {
        { const m = _Node$element(c, src); if (m !== null) return m; }
        break;
      }
    }
  } else if (k0.tokenType === '$keyword' || k0.tokenType === '$punct') {
    switch (src.charCodeAt(k0.offset)) {
    }
  } else {
    switch (k0.tokenType) {
      case "Comment": {
        { const m = _Node$comment(c, src); if (m !== null) return m; }
        break;
      }
      case "RawText": {
        { const m = _Node$rawText(c, src); if (m !== null) return m; }
        break;
      }
      case "Text": {
        { const m = _Node$text(c, src); if (m !== null) return m; }
        break;
      }
    }
  }
  throw new Error("matchNode: no arm matches" + ' @' + n.offset);
}

export type DocumentMatch =
  | { arm: "element"; alt: ({ branch: "element"; element: ElementNode } | { branch: "comment"; comment: CstLeaf } | { branch: "text"; text: CstLeaf })[] };

function _Document$element(c: readonly CstChild[], src: string): DocumentMatch | null {
  const alt: ({ branch: "element"; element: ElementNode } | { branch: "comment"; comment: CstLeaf } | { branch: "text"; text: CstLeaf })[] = [];
  let i = 0;
  for (;;) {
    const _t0 = i; let _t1 = true;
    _b2: {
      {
        let _t3 = false;
        if (!_t3) {
          let _t7_element: (ElementNode) | undefined;
          const _t4 = i; let _t5 = true;
          _b6: {
            if (!__nodeOf(c, i, "Element")) { _t5 = false; break _b6; }
            _t7_element = c[i] as ElementNode;
            i++;
          }
          if (_t5) { _t3 = true; alt.push({ branch: "element", element: _t7_element! } as never); }
          else i = _t4;
        }
        if (!_t3) {
          let _t11_comment: (CstLeaf) | undefined;
          const _t8 = i; let _t9 = true;
          _b10: {
            if (!(__tok(c, i, "Comment"))) { _t9 = false; break _b10; }
            _t11_comment = c[i] as CstLeaf;
            i++;
          }
          if (_t9) { _t3 = true; alt.push({ branch: "comment", comment: _t11_comment! } as never); }
          else i = _t8;
        }
        if (!_t3) {
          let _t15_text: (CstLeaf) | undefined;
          const _t12 = i; let _t13 = true;
          _b14: {
            if (!(__tok(c, i, "Text"))) { _t13 = false; break _b14; }
            _t15_text = c[i] as CstLeaf;
            i++;
          }
          if (_t13) { _t3 = true; alt.push({ branch: "text", text: _t15_text! } as never); }
          else i = _t12;
        }
        if (!_t3) { _t1 = false; break _b2; }
      }
    }
    if (!_t1) { i = _t0; break; }
    if (i === _t0) break;
  }
  if (i !== c.length) return null;
  return { arm: "element", alt };
}

export function matchDocument(n: DocumentNode, src: string): DocumentMatch {
  const c = n.children;
  const k0 = c[0] as (CstChild & { tokenType?: string; rule?: string }) | undefined;
  if (k0 === undefined) {
    { const m = _Document$element(c, src); if (m !== null) return m; }
  } else if (k0.tokenType === undefined) {
    switch (k0.rule) {
      case "Element": {
        { const m = _Document$element(c, src); if (m !== null) return m; }
        break;
      }
    }
  } else if (k0.tokenType === '$keyword' || k0.tokenType === '$punct') {
    switch (src.charCodeAt(k0.offset)) {
    }
  } else {
    switch (k0.tokenType) {
      case "Comment": {
        { const m = _Document$element(c, src); if (m !== null) return m; }
        break;
      }
      case "Text": {
        { const m = _Document$element(c, src); if (m !== null) return m; }
        break;
      }
    }
  }
  throw new Error("matchDocument: no arm matches" + ' @' + n.offset);
}

/** rule name → its matcher (generic walking; the totality gate uses this). */
export const MATCHERS: Record<string, (n: never, src: string) => { arm: string }> = {
  "Element": matchElement,
  "Attr": matchAttr,
  "Node": matchNode,
  "Document": matchDocument,
};
