// AUTO-GENERATED by src/gen-ast-types.ts — do not edit by hand.
// Typed CST for the parser output of this grammar.
//
// LIMITATION — no named fields: the grammar carries no labels on rule
// elements (e.g. `[$, '.', Ident]` has no field names), so children are
// typed by *kind* (which Node rules / leaf token types can appear), not as
// named accessors like `node.name`/`node.value`. Named-field accessors would
// require adding field labels to the grammar DSL (a future enrichment).

export interface CstPos {
  offset: number;
  end: number;
}

/** Every `tokenType` a CstLeaf in this grammar can carry. */
export type TokenType =
  | 'BigInt'
  | 'BinaryNumber'
  | 'BlockComment'
  | 'Decorator'
  | 'HexNumber'
  | 'Ident'
  | 'JSDoc'
  | 'JSXClose'
  | 'JSXSelfClose'
  | 'LineComment'
  | 'Number'
  | 'OctalNumber'
  | 'PrivateField'
  | 'Regex'
  | 'Shebang'
  | 'String'
  | 'Template'
  | 'TripleSlash'
  | '$keyword'
  | '$punct'
  | '$operator'
  | '$templateHead'
  | '$templateMiddle'
  | '$templateTail';

/** A terminal: one lexer token (or synthetic keyword/punct/operator leaf). */
export interface CstLeaf extends CstPos {
  tokenType: TokenType;
}

/** Synthetic node the parser builds for an interpolated template literal. */
export interface $templateNode extends CstPos {
  rule: '$template';
  children: CstChild[];
}

/** `DecoratorExpr` node. Children (flattened, in source order) are drawn from: */
export interface DecoratorExprNode extends CstPos {
  rule: 'DecoratorExpr';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Decorator' })
    | ExprNode
  >;
}

/** `Expr` node. Children (flattened, in source order) are drawn from: */
export interface ExprNode extends CstPos {
  rule: 'Expr';
  children: Array<
    | $templateNode
    | (CstLeaf & { tokenType: '$keyword' })
    | (CstLeaf & { tokenType: '$operator' })
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: '$templateHead' })
    | (CstLeaf & { tokenType: 'BigInt' })
    | (CstLeaf & { tokenType: 'BinaryNumber' })
    | (CstLeaf & { tokenType: 'HexNumber' })
    | (CstLeaf & { tokenType: 'Ident' })
    | (CstLeaf & { tokenType: 'Number' })
    | (CstLeaf & { tokenType: 'OctalNumber' })
    | (CstLeaf & { tokenType: 'PrivateField' })
    | (CstLeaf & { tokenType: 'Regex' })
    | (CstLeaf & { tokenType: 'String' })
    | (CstLeaf & { tokenType: 'Template' })
    | BlockNode
    | ClassHeritageNode
    | ClassMemberNode
    | DecoratorExprNode
    | ExprNode
    | JSXElementNode
    | NewTargetNode
    | ParamNode
    | PropNode
  >;
}

/** `Prop` node. Children (flattened, in source order) are drawn from: */
export interface PropNode extends CstPos {
  rule: 'Prop';
  children: Array<
    | (CstLeaf & { tokenType: '$keyword' })
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | BlockNode
    | ExprNode
    | MemberNameNode
    | ParamNode
  >;
}

/** `MemberName` node. Children (flattened, in source order) are drawn from: */
export interface MemberNameNode extends CstPos {
  rule: 'MemberName';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'BigInt' })
    | (CstLeaf & { tokenType: 'BinaryNumber' })
    | (CstLeaf & { tokenType: 'HexNumber' })
    | (CstLeaf & { tokenType: 'Ident' })
    | (CstLeaf & { tokenType: 'Number' })
    | (CstLeaf & { tokenType: 'OctalNumber' })
    | (CstLeaf & { tokenType: 'PrivateField' })
    | (CstLeaf & { tokenType: 'String' })
    | ExprNode
  >;
}

/** `NewTarget` node. Children (flattened, in source order) are drawn from: */
export interface NewTargetNode extends CstPos {
  rule: 'NewTarget';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | ExprNode
    | NewTargetNode
  >;
}

/** `ClassHeritage` node. Children (flattened, in source order) are drawn from: */
export interface ClassHeritageNode extends CstPos {
  rule: 'ClassHeritage';
  children: Array<
    | (CstLeaf & { tokenType: '$keyword' })
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | (CstLeaf & { tokenType: 'Number' })
    | (CstLeaf & { tokenType: 'String' })
    | ClassHeritageNode
    | ExprNode
  >;
}

/** `Stmt` node. Children (flattened, in source order) are drawn from: */
export interface StmtNode extends CstPos {
  rule: 'Stmt';
  children: Array<
    | (CstLeaf & { tokenType: '$keyword' })
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | BindingNode
    | BindingPatternNode
    | BlockNode
    | DeclNode
    | ExprNode
    | ForHeadNode
    | ParamNode
    | StmtNode
    | SwitchCaseNode
  >;
}

/** `Block` node. Children (flattened, in source order) are drawn from: */
export interface BlockNode extends CstPos {
  rule: 'Block';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | StmtNode
  >;
}

/** `BindingProperty` node. Children (flattened, in source order) are drawn from: */
export interface BindingPropertyNode extends CstPos {
  rule: 'BindingProperty';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | (CstLeaf & { tokenType: 'Number' })
    | (CstLeaf & { tokenType: 'String' })
    | BindingElementNode
    | BindingPatternNode
    | ExprNode
  >;
}

/** `BindingElement` node. Children (flattened, in source order) are drawn from: */
export interface BindingElementNode extends CstPos {
  rule: 'BindingElement';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | BindingPatternNode
    | ExprNode
  >;
}

/** `ArrayBindingElement` node. Children (flattened, in source order) are drawn from: */
export interface ArrayBindingElementNode extends CstPos {
  rule: 'ArrayBindingElement';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | BindingElementNode
    | BindingPatternNode
  >;
}

/** `BindingPattern` node. Children (flattened, in source order) are drawn from: */
export interface BindingPatternNode extends CstPos {
  rule: 'BindingPattern';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | ArrayBindingElementNode
    | BindingPropertyNode
  >;
}

/** `Binding` node. Children (flattened, in source order) are drawn from: */
export interface BindingNode extends CstPos {
  rule: 'Binding';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | BindingPatternNode
    | ExprNode
  >;
}

/** `ForBinding` node. Children (flattened, in source order) are drawn from: */
export interface ForBindingNode extends CstPos {
  rule: 'ForBinding';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | BindingPatternNode
    | ExprNode
  >;
}

/** `Param` node. Children (flattened, in source order) are drawn from: */
export interface ParamNode extends CstPos {
  rule: 'Param';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | BindingPatternNode
    | DecoratorExprNode
    | ExprNode
  >;
}

/** `ForHead` node. Children (flattened, in source order) are drawn from: */
export interface ForHeadNode extends CstPos {
  rule: 'ForHead';
  children: Array<
    | (CstLeaf & { tokenType: '$keyword' })
    | (CstLeaf & { tokenType: '$punct' })
    | ExprNode
    | ForBindingNode
  >;
}

/** `SwitchCase` node. Children (flattened, in source order) are drawn from: */
export interface SwitchCaseNode extends CstPos {
  rule: 'SwitchCase';
  children: Array<
    | (CstLeaf & { tokenType: '$keyword' })
    | (CstLeaf & { tokenType: '$punct' })
    | ExprNode
    | StmtNode
  >;
}

/** `Decl` node. Children (flattened, in source order) are drawn from: */
export interface DeclNode extends CstPos {
  rule: 'Decl';
  children: Array<
    | (CstLeaf & { tokenType: '$keyword' })
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | (CstLeaf & { tokenType: 'String' })
    | BlockNode
    | ClassHeritageNode
    | ClassMemberNode
    | DeclNode
    | DecoratorExprNode
    | ExprNode
    | ImportClauseNode
    | ImportSpecifierNode
    | ParamNode
    | StmtNode
  >;
}

/** `ClassMember` node. Children (flattened, in source order) are drawn from: */
export interface ClassMemberNode extends CstPos {
  rule: 'ClassMember';
  children: Array<
    | (CstLeaf & { tokenType: '$keyword' })
    | (CstLeaf & { tokenType: '$punct' })
    | BlockNode
    | DecoratorExprNode
    | ExprNode
    | MemberNameNode
    | ParamNode
  >;
}

/** `ImportClause` node. Children (flattened, in source order) are drawn from: */
export interface ImportClauseNode extends CstPos {
  rule: 'ImportClause';
  children: Array<
    | (CstLeaf & { tokenType: '$keyword' })
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | ImportSpecifierNode
  >;
}

/** `ImportSpecifier` node. Children (flattened, in source order) are drawn from: */
export interface ImportSpecifierNode extends CstPos {
  rule: 'ImportSpecifier';
  children: Array<
    | (CstLeaf & { tokenType: '$keyword' })
    | (CstLeaf & { tokenType: 'Ident' })
  >;
}

/** `JSXTagName` node. Children (flattened, in source order) are drawn from: */
export interface JSXTagNameNode extends CstPos {
  rule: 'JSXTagName';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
  >;
}

/** `JSXAttrValue` node. Children (flattened, in source order) are drawn from: */
export interface JSXAttrValueNode extends CstPos {
  rule: 'JSXAttrValue';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'String' })
    | ExprNode
  >;
}

/** `JSXAttr` node. Children (flattened, in source order) are drawn from: */
export interface JSXAttrNode extends CstPos {
  rule: 'JSXAttr';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | ExprNode
    | JSXAttrValueNode
  >;
}

/** `JSXContainer` node. Children (flattened, in source order) are drawn from: */
export interface JSXContainerNode extends CstPos {
  rule: 'JSXContainer';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | ExprNode
  >;
}

/** `JSXChild` node. Children (flattened, in source order) are drawn from: */
export interface JSXChildNode extends CstPos {
  rule: 'JSXChild';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Ident' })
    | (CstLeaf & { tokenType: 'Number' })
    | (CstLeaf & { tokenType: 'String' })
    | JSXContainerNode
    | JSXElementNode
  >;
}

/** `JSXElement` node. Children (flattened, in source order) are drawn from: */
export interface JSXElementNode extends CstPos {
  rule: 'JSXElement';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'JSXClose' })
    | (CstLeaf & { tokenType: 'JSXSelfClose' })
    | JSXAttrNode
    | JSXChildNode
    | JSXTagNameNode
  >;
}

/** `Program` node. Children (flattened, in source order) are drawn from: */
export interface ProgramNode extends CstPos {
  rule: 'Program';
  children: Array<
    | DeclNode
    | StmtNode
  >;
}

/** Discriminated union of every node kind. Switch on `node.rule` for exhaustiveness. */
export type CstNode =
  | $templateNode
  | DecoratorExprNode
  | ExprNode
  | PropNode
  | MemberNameNode
  | NewTargetNode
  | ClassHeritageNode
  | StmtNode
  | BlockNode
  | BindingPropertyNode
  | BindingElementNode
  | ArrayBindingElementNode
  | BindingPatternNode
  | BindingNode
  | ForBindingNode
  | ParamNode
  | ForHeadNode
  | SwitchCaseNode
  | DeclNode
  | ClassMemberNode
  | ImportClauseNode
  | ImportSpecifierNode
  | JSXTagNameNode
  | JSXAttrValueNode
  | JSXAttrNode
  | JSXContainerNode
  | JSXChildNode
  | JSXElementNode
  | ProgramNode;

/** Every `rule` discriminant value (the keys of the CstNode union). */
export type RuleName =
  | '$template'
  | 'DecoratorExpr'
  | 'Expr'
  | 'Prop'
  | 'MemberName'
  | 'NewTarget'
  | 'ClassHeritage'
  | 'Stmt'
  | 'Block'
  | 'BindingProperty'
  | 'BindingElement'
  | 'ArrayBindingElement'
  | 'BindingPattern'
  | 'Binding'
  | 'ForBinding'
  | 'Param'
  | 'ForHead'
  | 'SwitchCase'
  | 'Decl'
  | 'ClassMember'
  | 'ImportClause'
  | 'ImportSpecifier'
  | 'JSXTagName'
  | 'JSXAttrValue'
  | 'JSXAttr'
  | 'JSXContainer'
  | 'JSXChild'
  | 'JSXElement'
  | 'Program';

/** Any CST element: a node or a leaf. */
export type CstChild = CstNode | CstLeaf;

/** Narrow the CstNode union to the node for a given rule name. */
export type NodeOf<R extends RuleName> = Extract<CstNode, { rule: R }>;
