// AUTO-GENERATED by src/gen-ast-types.ts — do not edit by hand.
// Typed CST for the parser output of this grammar.
//
// LIMITATION — no named fields: the grammar carries no labels on rule
// elements (e.g. `[$, '.', Ident]` has no field names), so children are
// typed by *kind* (which Node rules / leaf token types can appear), not as
// named accessors like `node.name`/`node.value`. Named-field accessors would
// require adding field labels to the grammar DSL (a future enrichment).

export interface CstPos {
  offset: number;
  end: number;
}

/** Every `tokenType` a CstLeaf in this grammar can carry. */
export type TokenType =
  | 'Alias'
  | 'Anchor'
  | 'BlockScalar'
  | 'BoolNull'
  | 'Comment'
  | 'DQuote'
  | 'DQuoteKey'
  | 'Dedent'
  | 'Directive'
  | 'DocEnd'
  | 'DocStart'
  | 'Indent'
  | 'Key'
  | 'Newline'
  | 'Num'
  | 'Plain'
  | 'SQuote'
  | 'SQuoteKey'
  | 'Tag'
  | 'YamlDirective'
  | '$keyword'
  | '$punct'
  | '$operator'
  | '$templateHead'
  | '$templateMiddle'
  | '$templateTail';

/** A terminal: one lexer token (or synthetic keyword/punct/operator leaf). */
export interface CstLeaf extends CstPos {
  kind: 'leaf';
  tokenType: TokenType;
  text: string;
}

/** `Property` node. Children (flattened, in source order) are drawn from: */
export interface PropertyNode extends CstPos {
  kind: 'node';
  rule: 'Property';
  children: Array<
    | (CstLeaf & { tokenType: 'Anchor' })
    | (CstLeaf & { tokenType: 'Tag' })
  >;
}

/** `ContentNode` node. Children (flattened, in source order) are drawn from: */
export interface ContentNodeNode extends CstPos {
  kind: 'node';
  rule: 'ContentNode';
  children: Array<
    | AliasOrKeyedNode
    | BlockSequenceNode
    | EmptyKeyMappingNode
    | ExplicitMappingNode
    | FlowMappingNode
    | FlowSequenceNode
    | MappingFromFlowNode
    | MappingOrScalarNode
  >;
}

/** `Node` node. Children (flattened, in source order) are drawn from: */
export interface NodeNode extends CstPos {
  kind: 'node';
  rule: 'Node';
  children: Array<
    | (CstLeaf & { tokenType: 'Anchor' })
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | (CstLeaf & { tokenType: 'Newline' })
    | (CstLeaf & { tokenType: 'Tag' })
    | AliasOrKeyedNode
    | BlockSequenceNode
    | EmptyKeyMappingNode
    | ExplicitMappingNode
    | FlowMappingNode
    | FlowSequenceNode
    | MappingFromFlowNode
    | MappingOrScalarNode
    | NodeNode
  >;
}

/** `MappingOrScalar` node. Children (flattened, in source order) are drawn from: */
export interface MappingOrScalarNode extends CstPos {
  kind: 'node';
  rule: 'MappingOrScalar';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'BoolNull' })
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | (CstLeaf & { tokenType: 'Newline' })
    | (CstLeaf & { tokenType: 'Num' })
    | (CstLeaf & { tokenType: 'Plain' })
    | BlockKeyScalarNode
    | MapEntryNode
    | MapValueNode
    | ScalarNode
  >;
}

/** `AliasOrKeyed` node. Children (flattened, in source order) are drawn from: */
export interface AliasOrKeyedNode extends CstPos {
  kind: 'node';
  rule: 'AliasOrKeyed';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Alias' })
    | (CstLeaf & { tokenType: 'Newline' })
    | MapEntryNode
    | MapValueNode
  >;
}

/** `BlockKey` node. Children (flattened, in source order) are drawn from: */
export interface BlockKeyNode extends CstPos {
  kind: 'node';
  rule: 'BlockKey';
  children: Array<
    | (CstLeaf & { tokenType: 'Alias' })
    | BlockKeyScalarNode
    | FlowMappingNode
    | FlowSequenceNode
    | PropertyNode
  >;
}

/** `ExplicitEntry` node. Children (flattened, in source order) are drawn from: */
export interface ExplicitEntryNode extends CstPos {
  kind: 'node';
  rule: 'ExplicitEntry';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Newline' })
    | MapValueNode
  >;
}

/** `MapEntry` node. Children (flattened, in source order) are drawn from: */
export interface MapEntryNode extends CstPos {
  kind: 'node';
  rule: 'MapEntry';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | BlockKeyNode
    | ExplicitEntryNode
    | MapValueNode
  >;
}

/** `MapEntryNoEmpty` node. Children (flattened, in source order) are drawn from: */
export interface MapEntryNoEmptyNode extends CstPos {
  kind: 'node';
  rule: 'MapEntryNoEmpty';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | BlockKeyNode
    | ExplicitEntryNode
    | MapValueNode
  >;
}

/** `ExplicitMapping` node. Children (flattened, in source order) are drawn from: */
export interface ExplicitMappingNode extends CstPos {
  kind: 'node';
  rule: 'ExplicitMapping';
  children: Array<
    | (CstLeaf & { tokenType: 'Newline' })
    | ExplicitEntryNode
    | MapEntryNode
  >;
}

/** `EmptyKeyMapping` node. Children (flattened, in source order) are drawn from: */
export interface EmptyKeyMappingNode extends CstPos {
  kind: 'node';
  rule: 'EmptyKeyMapping';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Newline' })
    | MapEntryNoEmptyNode
    | MapValueNode
  >;
}

/** `Value` node. Children (flattened, in source order) are drawn from: */
export interface ValueNode extends CstPos {
  kind: 'node';
  rule: 'Value';
  children: Array<
    | (CstLeaf & { tokenType: 'BoolNull' })
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | (CstLeaf & { tokenType: 'Newline' })
    | (CstLeaf & { tokenType: 'Num' })
    | (CstLeaf & { tokenType: 'Plain' })
    | NodeNode
    | SeqValueNodeNode
  >;
}

/** `MapValue` node. Children (flattened, in source order) are drawn from: */
export interface MapValueNode extends CstPos {
  kind: 'node';
  rule: 'MapValue';
  children: Array<
    | (CstLeaf & { tokenType: 'BoolNull' })
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | (CstLeaf & { tokenType: 'Newline' })
    | (CstLeaf & { tokenType: 'Num' })
    | (CstLeaf & { tokenType: 'Plain' })
    | BlockSequenceNode
    | MapValueNodeNode
    | NodeNode
    | PropertyNode
  >;
}

/** `IndentedValueNode` node. Children (flattened, in source order) are drawn from: */
export interface IndentedValueNodeNode extends CstPos {
  kind: 'node';
  rule: 'IndentedValueNode';
  children: Array<
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | CollectionContentNode
    | ContentNodeNode
    | IndentedValueNodeNode
    | PropertyNode
  >;
}

/** `CollectionContent` node. Children (flattened, in source order) are drawn from: */
export interface CollectionContentNode extends CstPos {
  kind: 'node';
  rule: 'CollectionContent';
  children: Array<
    | BlockSequenceNode
    | ExplicitMappingNode
    | FlowMappingNode
    | FlowSequenceNode
    | MappingFromFlowNode
    | MappingFromScalarNode
  >;
}

/** `MappingFromScalar` node. Children (flattened, in source order) are drawn from: */
export interface MappingFromScalarNode extends CstPos {
  kind: 'node';
  rule: 'MappingFromScalar';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Newline' })
    | BlockKeyScalarNode
    | MapEntryNode
    | MapValueNode
  >;
}

/** `MappingFromFlow` node. Children (flattened, in source order) are drawn from: */
export interface MappingFromFlowNode extends CstPos {
  kind: 'node';
  rule: 'MappingFromFlow';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Newline' })
    | FlowMappingNode
    | FlowSequenceNode
    | MapEntryNode
    | MapValueNode
  >;
}

/** `MapValueNode` node. Children (flattened, in source order) are drawn from: */
export interface MapValueNodeNode extends CstPos {
  kind: 'node';
  rule: 'MapValueNode';
  children: Array<
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | IndentedValueNodeNode
    | MapInlineContentNode
    | PropertyNode
  >;
}

/** `MapInlineContent` node. Children (flattened, in source order) are drawn from: */
export interface MapInlineContentNode extends CstPos {
  kind: 'node';
  rule: 'MapInlineContent';
  children: Array<
    | (CstLeaf & { tokenType: 'Alias' })
    | FlowMappingNode
    | FlowSequenceNode
    | MappingOrScalarNode
  >;
}

/** `SeqValueNode` node. Children (flattened, in source order) are drawn from: */
export interface SeqValueNodeNode extends CstPos {
  kind: 'node';
  rule: 'SeqValueNode';
  children: Array<
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | IndentedValueNodeNode
    | PropertyNode
    | SeqInlineContentNode
  >;
}

/** `SeqInlineContent` node. Children (flattened, in source order) are drawn from: */
export interface SeqInlineContentNode extends CstPos {
  kind: 'node';
  rule: 'SeqInlineContent';
  children: Array<
    | (CstLeaf & { tokenType: 'Alias' })
    | BlockSequenceNode
    | EmptyKeyMappingNode
    | FlowMappingNode
    | FlowSequenceNode
    | MappingOrScalarNode
  >;
}

/** `BlockSequence` node. Children (flattened, in source order) are drawn from: */
export interface BlockSequenceNode extends CstPos {
  kind: 'node';
  rule: 'BlockSequence';
  children: Array<
    | (CstLeaf & { tokenType: 'Newline' })
    | SeqItemNode
  >;
}

/** `SeqItem` node. Children (flattened, in source order) are drawn from: */
export interface SeqItemNode extends CstPos {
  kind: 'node';
  rule: 'SeqItem';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | ValueNode
  >;
}

/** `FlowNode` node. Children (flattened, in source order) are drawn from: */
export interface FlowNodeNode extends CstPos {
  kind: 'node';
  rule: 'FlowNode';
  children: Array<
    | (CstLeaf & { tokenType: 'Alias' })
    | FlowMappingNode
    | FlowSequenceNode
    | PropertyNode
    | ScalarNode
  >;
}

/** `FlowExplicit` node. Children (flattened, in source order) are drawn from: */
export interface FlowExplicitNode extends CstPos {
  kind: 'node';
  rule: 'FlowExplicit';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | FlowNodeNode
  >;
}

/** `FlowMapEntry` node. Children (flattened, in source order) are drawn from: */
export interface FlowMapEntryNode extends CstPos {
  kind: 'node';
  rule: 'FlowMapEntry';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | FlowExplicitNode
    | FlowNodeNode
  >;
}

/** `FlowMapping` node. Children (flattened, in source order) are drawn from: */
export interface FlowMappingNode extends CstPos {
  kind: 'node';
  rule: 'FlowMapping';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | FlowMapEntryNode
  >;
}

/** `FlowSeqEntry` node. Children (flattened, in source order) are drawn from: */
export interface FlowSeqEntryNode extends CstPos {
  kind: 'node';
  rule: 'FlowSeqEntry';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | FlowNodeNode
    | FlowSeqKeyNode
  >;
}

/** `FlowSeqKey` node. Children (flattened, in source order) are drawn from: */
export interface FlowSeqKeyNode extends CstPos {
  kind: 'node';
  rule: 'FlowSeqKey';
  children: Array<
    | (CstLeaf & { tokenType: 'Alias' })
    | (CstLeaf & { tokenType: 'DQuoteKey' })
    | (CstLeaf & { tokenType: 'Key' })
    | (CstLeaf & { tokenType: 'SQuoteKey' })
    | FlowMappingNode
    | FlowSequenceNode
    | PropertyNode
  >;
}

/** `FlowSequence` node. Children (flattened, in source order) are drawn from: */
export interface FlowSequenceNode extends CstPos {
  kind: 'node';
  rule: 'FlowSequence';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | FlowSeqEntryNode
  >;
}

/** `Scalar` node. Children (flattened, in source order) are drawn from: */
export interface ScalarNode extends CstPos {
  kind: 'node';
  rule: 'Scalar';
  children: Array<
    | (CstLeaf & { tokenType: 'BlockScalar' })
    | (CstLeaf & { tokenType: 'BoolNull' })
    | (CstLeaf & { tokenType: 'DQuote' })
    | (CstLeaf & { tokenType: 'DQuoteKey' })
    | (CstLeaf & { tokenType: 'Key' })
    | (CstLeaf & { tokenType: 'Num' })
    | (CstLeaf & { tokenType: 'Plain' })
    | (CstLeaf & { tokenType: 'SQuote' })
    | (CstLeaf & { tokenType: 'SQuoteKey' })
  >;
}

/** `BlockKeyScalar` node. Children (flattened, in source order) are drawn from: */
export interface BlockKeyScalarNode extends CstPos {
  kind: 'node';
  rule: 'BlockKeyScalar';
  children: Array<
    | (CstLeaf & { tokenType: 'BoolNull' })
    | (CstLeaf & { tokenType: 'DQuoteKey' })
    | (CstLeaf & { tokenType: 'Key' })
    | (CstLeaf & { tokenType: 'Num' })
    | (CstLeaf & { tokenType: 'Plain' })
    | (CstLeaf & { tokenType: 'SQuoteKey' })
  >;
}

/** `DocFold` node. Children (flattened, in source order) are drawn from: */
export interface DocFoldNode extends CstPos {
  kind: 'node';
  rule: 'DocFold';
  children: Array<
    | (CstLeaf & { tokenType: 'BoolNull' })
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Directive' })
    | (CstLeaf & { tokenType: 'Indent' })
    | (CstLeaf & { tokenType: 'Newline' })
    | (CstLeaf & { tokenType: 'Num' })
    | (CstLeaf & { tokenType: 'Plain' })
    | (CstLeaf & { tokenType: 'YamlDirective' })
  >;
}

/** `InlineDocNode` node. Children (flattened, in source order) are drawn from: */
export interface InlineDocNodeNode extends CstPos {
  kind: 'node';
  rule: 'InlineDocNode';
  children: Array<
    | (CstLeaf & { tokenType: 'Alias' })
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | (CstLeaf & { tokenType: 'Newline' })
    | DocFoldNode
    | FlowMappingNode
    | FlowSequenceNode
    | NodeNode
    | PropertyNode
    | ScalarNode
  >;
}

/** `ExplicitDocBody` node. Children (flattened, in source order) are drawn from: */
export interface ExplicitDocBodyNode extends CstPos {
  kind: 'node';
  rule: 'ExplicitDocBody';
  children: Array<
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | (CstLeaf & { tokenType: 'Newline' })
    | DocFoldNode
    | InlineDocNodeNode
    | NodeNode
  >;
}

/** `AfterDocEnd` node. Children (flattened, in source order) are drawn from: */
export interface AfterDocEndNode extends CstPos {
  kind: 'node';
  rule: 'AfterDocEnd';
  children: Array<
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Directive' })
    | (CstLeaf & { tokenType: 'DocStart' })
    | (CstLeaf & { tokenType: 'Indent' })
    | (CstLeaf & { tokenType: 'Newline' })
    | (CstLeaf & { tokenType: 'YamlDirective' })
    | DocFoldNode
    | ExplicitDocBodyNode
    | NodeNode
  >;
}

/** `NextDoc` node. Children (flattened, in source order) are drawn from: */
export interface NextDocNode extends CstPos {
  kind: 'node';
  rule: 'NextDoc';
  children: Array<
    | (CstLeaf & { tokenType: 'DocEnd' })
    | (CstLeaf & { tokenType: 'DocStart' })
    | (CstLeaf & { tokenType: 'Newline' })
    | AfterDocEndNode
    | ExplicitDocBodyNode
  >;
}

/** `Stream` node. Children (flattened, in source order) are drawn from: */
export interface StreamNode extends CstPos {
  kind: 'node';
  rule: 'Stream';
  children: Array<
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Directive' })
    | (CstLeaf & { tokenType: 'DocEnd' })
    | (CstLeaf & { tokenType: 'DocStart' })
    | (CstLeaf & { tokenType: 'Indent' })
    | (CstLeaf & { tokenType: 'Newline' })
    | (CstLeaf & { tokenType: 'YamlDirective' })
    | DocFoldNode
    | ExplicitDocBodyNode
    | NextDocNode
    | NodeNode
  >;
}

/** Discriminated union of every node kind. Switch on `node.rule` for exhaustiveness. */
export type CstNode =
  | PropertyNode
  | ContentNodeNode
  | NodeNode
  | MappingOrScalarNode
  | AliasOrKeyedNode
  | BlockKeyNode
  | ExplicitEntryNode
  | MapEntryNode
  | MapEntryNoEmptyNode
  | ExplicitMappingNode
  | EmptyKeyMappingNode
  | ValueNode
  | MapValueNode
  | IndentedValueNodeNode
  | CollectionContentNode
  | MappingFromScalarNode
  | MappingFromFlowNode
  | MapValueNodeNode
  | MapInlineContentNode
  | SeqValueNodeNode
  | SeqInlineContentNode
  | BlockSequenceNode
  | SeqItemNode
  | FlowNodeNode
  | FlowExplicitNode
  | FlowMapEntryNode
  | FlowMappingNode
  | FlowSeqEntryNode
  | FlowSeqKeyNode
  | FlowSequenceNode
  | ScalarNode
  | BlockKeyScalarNode
  | DocFoldNode
  | InlineDocNodeNode
  | ExplicitDocBodyNode
  | AfterDocEndNode
  | NextDocNode
  | StreamNode;

/** Every `rule` discriminant value (the keys of the CstNode union). */
export type RuleName =
  | 'Property'
  | 'ContentNode'
  | 'Node'
  | 'MappingOrScalar'
  | 'AliasOrKeyed'
  | 'BlockKey'
  | 'ExplicitEntry'
  | 'MapEntry'
  | 'MapEntryNoEmpty'
  | 'ExplicitMapping'
  | 'EmptyKeyMapping'
  | 'Value'
  | 'MapValue'
  | 'IndentedValueNode'
  | 'CollectionContent'
  | 'MappingFromScalar'
  | 'MappingFromFlow'
  | 'MapValueNode'
  | 'MapInlineContent'
  | 'SeqValueNode'
  | 'SeqInlineContent'
  | 'BlockSequence'
  | 'SeqItem'
  | 'FlowNode'
  | 'FlowExplicit'
  | 'FlowMapEntry'
  | 'FlowMapping'
  | 'FlowSeqEntry'
  | 'FlowSeqKey'
  | 'FlowSequence'
  | 'Scalar'
  | 'BlockKeyScalar'
  | 'DocFold'
  | 'InlineDocNode'
  | 'ExplicitDocBody'
  | 'AfterDocEnd'
  | 'NextDoc'
  | 'Stream';

/** Any CST element: a node or a leaf. */
export type CstChild = CstNode | CstLeaf;

/** Narrow the CstNode union to the node for a given rule name. */
export type NodeOf<R extends RuleName> = Extract<CstNode, { rule: R }>;
