// AUTO-GENERATED by src/gen-ast-types.ts — do not edit by hand.
// Typed CST for the parser output of this grammar.
//
// LIMITATION — no named fields: the grammar carries no labels on rule
// elements (e.g. `[$, '.', Ident]` has no field names), so children are
// typed by *kind* (which Node rules / leaf token types can appear), not as
// named accessors like `node.name`/`node.value`. Named-field accessors would
// require adding field labels to the grammar DSL (a future enrichment).

export interface CstPos {
  offset: number;
  end: number;
}

/** Every `tokenType` a CstLeaf in this grammar can carry. */
export type TokenType =
  | 'Alias'
  | 'Anchor'
  | 'BlockScalar'
  | 'BoolNull'
  | 'Comment'
  | 'DQuote'
  | 'DQuoteKey'
  | 'Dedent'
  | 'Directive'
  | 'DocEnd'
  | 'DocStart'
  | 'Indent'
  | 'Key'
  | 'Newline'
  | 'Num'
  | 'Plain'
  | 'SQuote'
  | 'SQuoteKey'
  | 'Tag'
  | '$keyword'
  | '$punct'
  | '$operator'
  | '$templateHead'
  | '$templateMiddle'
  | '$templateTail';

/** A terminal: one lexer token (or synthetic keyword/punct/operator leaf). */
export interface CstLeaf extends CstPos {
  kind: 'leaf';
  tokenType: TokenType;
  text: string;
}

/** `Node` node. Children (flattened, in source order) are drawn from: */
export interface NodeNode extends CstPos {
  kind: 'node';
  rule: 'Node';
  children: Array<
    | (CstLeaf & { tokenType: 'Alias' })
    | (CstLeaf & { tokenType: 'Anchor' })
    | (CstLeaf & { tokenType: 'Tag' })
    | BlockSequenceNode
    | ExplicitMappingNode
    | FlowMappingNode
    | FlowSequenceNode
    | MappingOrScalarNode
  >;
}

/** `MappingOrScalar` node. Children (flattened, in source order) are drawn from: */
export interface MappingOrScalarNode extends CstPos {
  kind: 'node';
  rule: 'MappingOrScalar';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Newline' })
    | MapEntryNode
    | MapValueNode
    | ScalarNode
  >;
}

/** `MapEntry` node. Children (flattened, in source order) are drawn from: */
export interface MapEntryNode extends CstPos {
  kind: 'node';
  rule: 'MapEntry';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Newline' })
    | MapValueNode
    | ScalarNode
  >;
}

/** `ExplicitMapping` node. Children (flattened, in source order) are drawn from: */
export interface ExplicitMappingNode extends CstPos {
  kind: 'node';
  rule: 'ExplicitMapping';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | (CstLeaf & { tokenType: 'Newline' })
    | MapEntryNode
    | MapValueNode
  >;
}

/** `Value` node. Children (flattened, in source order) are drawn from: */
export interface ValueNode extends CstPos {
  kind: 'node';
  rule: 'Value';
  children: Array<
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | NodeNode
  >;
}

/** `MapValue` node. Children (flattened, in source order) are drawn from: */
export interface MapValueNode extends CstPos {
  kind: 'node';
  rule: 'MapValue';
  children: Array<
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Indent' })
    | InlineNodeNode
    | NodeNode
  >;
}

/** `InlineNode` node. Children (flattened, in source order) are drawn from: */
export interface InlineNodeNode extends CstPos {
  kind: 'node';
  rule: 'InlineNode';
  children: Array<
    | (CstLeaf & { tokenType: 'Alias' })
    | (CstLeaf & { tokenType: 'Anchor' })
    | (CstLeaf & { tokenType: 'Tag' })
    | FlowMappingNode
    | FlowSequenceNode
    | MappingOrScalarNode
  >;
}

/** `BlockSequence` node. Children (flattened, in source order) are drawn from: */
export interface BlockSequenceNode extends CstPos {
  kind: 'node';
  rule: 'BlockSequence';
  children: Array<
    | (CstLeaf & { tokenType: 'Newline' })
    | SeqItemNode
  >;
}

/** `SeqItem` node. Children (flattened, in source order) are drawn from: */
export interface SeqItemNode extends CstPos {
  kind: 'node';
  rule: 'SeqItem';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | ValueNode
  >;
}

/** `FlowMapping` node. Children (flattened, in source order) are drawn from: */
export interface FlowMappingNode extends CstPos {
  kind: 'node';
  rule: 'FlowMapping';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | FlowEntryNode
  >;
}

/** `FlowEntry` node. Children (flattened, in source order) are drawn from: */
export interface FlowEntryNode extends CstPos {
  kind: 'node';
  rule: 'FlowEntry';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | FlowScalarOrNodeNode
    | FlowValueNode
  >;
}

/** `FlowValue` node. Children (flattened, in source order) are drawn from: */
export interface FlowValueNode extends CstPos {
  kind: 'node';
  rule: 'FlowValue';
  children: Array<
    | (CstLeaf & { tokenType: 'Alias' })
    | FlowMappingNode
    | FlowSequenceNode
    | ScalarNode
  >;
}

/** `FlowScalarOrNode` node. Children (flattened, in source order) are drawn from: */
export interface FlowScalarOrNodeNode extends CstPos {
  kind: 'node';
  rule: 'FlowScalarOrNode';
  children: Array<
    | (CstLeaf & { tokenType: 'Alias' })
    | FlowMappingNode
    | FlowSequenceNode
    | ScalarNode
  >;
}

/** `FlowSequence` node. Children (flattened, in source order) are drawn from: */
export interface FlowSequenceNode extends CstPos {
  kind: 'node';
  rule: 'FlowSequence';
  children: Array<
    | (CstLeaf & { tokenType: '$punct' })
    | FlowValueNode
  >;
}

/** `Scalar` node. Children (flattened, in source order) are drawn from: */
export interface ScalarNode extends CstPos {
  kind: 'node';
  rule: 'Scalar';
  children: Array<
    | (CstLeaf & { tokenType: 'BlockScalar' })
    | (CstLeaf & { tokenType: 'BoolNull' })
    | (CstLeaf & { tokenType: 'DQuote' })
    | (CstLeaf & { tokenType: 'DQuoteKey' })
    | (CstLeaf & { tokenType: 'Key' })
    | (CstLeaf & { tokenType: 'Num' })
    | (CstLeaf & { tokenType: 'Plain' })
    | (CstLeaf & { tokenType: 'SQuote' })
    | (CstLeaf & { tokenType: 'SQuoteKey' })
  >;
}

/** `Stream` node. Children (flattened, in source order) are drawn from: */
export interface StreamNode extends CstPos {
  kind: 'node';
  rule: 'Stream';
  children: Array<
    | (CstLeaf & { tokenType: 'Dedent' })
    | (CstLeaf & { tokenType: 'Directive' })
    | (CstLeaf & { tokenType: 'DocEnd' })
    | (CstLeaf & { tokenType: 'DocStart' })
    | (CstLeaf & { tokenType: 'Indent' })
    | (CstLeaf & { tokenType: 'Newline' })
    | NodeNode
  >;
}

/** Discriminated union of every node kind. Switch on `node.rule` for exhaustiveness. */
export type CstNode =
  | NodeNode
  | MappingOrScalarNode
  | MapEntryNode
  | ExplicitMappingNode
  | ValueNode
  | MapValueNode
  | InlineNodeNode
  | BlockSequenceNode
  | SeqItemNode
  | FlowMappingNode
  | FlowEntryNode
  | FlowValueNode
  | FlowScalarOrNodeNode
  | FlowSequenceNode
  | ScalarNode
  | StreamNode;

/** Every `rule` discriminant value (the keys of the CstNode union). */
export type RuleName =
  | 'Node'
  | 'MappingOrScalar'
  | 'MapEntry'
  | 'ExplicitMapping'
  | 'Value'
  | 'MapValue'
  | 'InlineNode'
  | 'BlockSequence'
  | 'SeqItem'
  | 'FlowMapping'
  | 'FlowEntry'
  | 'FlowValue'
  | 'FlowScalarOrNode'
  | 'FlowSequence'
  | 'Scalar'
  | 'Stream';

/** Any CST element: a node or a leaf. */
export type CstChild = CstNode | CstLeaf;

/** Narrow the CstNode union to the node for a given rule name. */
export type NodeOf<R extends RuleName> = Extract<CstNode, { rule: R }>;
