;; -----------------------------------------------------------------
;; Tree-sitter highlight queries generated by monogram.
;; Capture names follow the standard tree-sitter highlight vocabulary
;; (@keyword, @function, @type, @string, @property, @operator, …).
;; Inferred from rule SHAPES + the grammar's `scopes` section — the same
;; structural inference the TextMate generator uses.
;; -----------------------------------------------------------------

;; Bare identifier (lowest priority; specific patterns below win).
(ident) @variable

;; Declaration names (via the `name` field) → @function / @type.
(expr name: (ident) @type)
(expr name: (ident) @function)
(decl name: (ident) @function)
(decl name: (ident) @type)

;; Literal token nodes.
(shebang) @comment
(jsdoc) @comment.documentation
(triple_slash) @comment
(line_comment) @comment
(block_comment) @comment
(hex_number) @number
(octal_number) @number
(binary_number) @number
(big_int) @number
(number) @number
(string) @string
(template) @string
(regex_literal) @string.regexp
(decorator) @function.macro
(private_field) @property

;; Well-known property names.
((ident) @property.builtin
  (#any-of? @property.builtin "length" "prototype" "constructor"))

;; Keyword, operator, and punctuation literals.
[
  "implements" "interface" "namespace" "protected" "debugger" "readonly" "abstract" "override"
  "accessor" "private" "declare" "extends" "module" "public" "static" "unique"
  "const" "using" "class" "async" "with" "type" "enum" "meta"
  "let" "var" "get" "set" "out"
] @keyword
[
  "constructor" "function" "=>"
] @keyword.function
[
  "import" "export" "from"
] @keyword.import
[
  "default" "switch" "else" "case" "if"
] @keyword.conditional
[
  "while" "for" "do" "in" "of"
] @keyword.repeat
[
  "continue" "return" "break" "await" "yield"
] @keyword.return
[
  "finally" "catch" "throw" "try"
] @keyword.exception
[
  "instanceof" "satisfies" "asserts" "typeof" "delete" "keyof" "infer" "void"
  "new" "as" "is"
] @keyword.operator
[
  "Function" "Promise" "WeakMap" "WeakSet" "RegExp" "Object" "Symbol" "Array"
  "Error" "Date" "Map" "Set"
] @type
[
  "boolean" "unknown" "string" "number" "object" "symbol" "bigint" "never"
  "any"
] @type.builtin
[
  "undefined" "false" "true" "null"
] @constant.builtin
[
  "globalThis" "document" "console" "process" "require" "exports" "window" "global"
  "super" "this"
] @variable.builtin
[
  ">>>=" "**=" "<<=" ">>=" "??=" "||=" "&&=" "==="
  "!==" ">>>" "+=" "-=" "*=" "/=" "%=" "&="
  "|=" "^=" "==" "!=" "||" "&&" "??" "**"
  "++" "--" "<<" ">>" "<=" ">=" "=" "+"
  "-" "*" "/" "%" "!" "~" "|" "&"
  "^" "<" ">"
] @operator
[
  "(" ")" "{" "}" "[" "]"
] @punctuation.bracket
[
  "..." "?." ";" "," "?" ":"
] @punctuation.delimiter
