;; -----------------------------------------------------------------
;; Tree-sitter highlight queries generated by monogram.
;; Capture names follow the standard tree-sitter highlight vocabulary
;; (@keyword, @function, @type, @string, @property, @operator, …).
;; Inferred from rule SHAPES + the grammar's `scopes` section — the same
;; structural inference the TextMate generator uses.
;; -----------------------------------------------------------------

;; Bare identifier (lowest priority; specific patterns below win).
(ident) @variable

;; Declaration names (via the `name` field) → @function / @type.
(expr name: (ident) @type)
(expr name: (ident) @function)
(decl name: (ident) @function)
(decl name: (ident) @type)

;; Declaration names, keyword-anchored (disambiguates shared decl rules).
(expr "class" (ident) @type)
(expr "function" (ident) @function)
(decl "function" (ident) @function)
(decl "interface" (ident) @type)
(decl "type" (ident) @type)
(decl "class" (ident) @type)
(decl "enum" (ident) @type)
(decl "namespace" (ident) @type)

;; Type-reference identifiers (inside a type node) -> @type.
(type (ident) @type)

;; Structural member / type-param / property-access captures.
(jsxtag_name (ident) @type)
(type_param (ident) @type)
(member_name (ident) @property)
(type_member (ident) @property)
(expr (expr) (ident) @property)
(binding_property (ident) @property (binding_element))

;; Enum-like value members (override member-key, which would say @property).
(enum_member (member_name (ident) @variable))

;; Literal token nodes.
(shebang) @comment
(jsdoc) @comment.documentation
(triple_slash) @comment
(line_comment) @comment
(block_comment) @comment
(hex_number) @number
(octal_number) @number
(binary_number) @number
(big_int) @number
(number) @number
(string) @string
(template_chars) @string
(regex_literal) @string.regexp
(decorator) @function.macro
(private_field) @property
(template "`") @string
(template_substitution "${") @punctuation.special
(template_substitution "}") @punctuation.special

;; Well-known property names.
((ident) @property.builtin
  (#any-of? @property.builtin "length" "prototype" "constructor"))

;; Builtin / global / constant identifier names.
((ident) @variable.builtin
  (#any-of? @variable.builtin "console" "window" "document" "process" "require" "exports" "global" "globalThis"))

;; Keyword, operator, and punctuation literals.
[
  "implements" "interface" "namespace" "protected" "debugger" "readonly" "abstract" "override"
  "accessor" "private" "declare" "extends" "default" "module" "public" "static"
  "unique" "switch" "export" "const" "using" "class" "async" "with"
  "type" "enum" "meta" "case" "from" "let" "var" "get"
  "set" "out"
] @keyword
[
  "constructor" "function" "=>"
] @keyword.function
"import" @keyword.import
[
  "else" "if"
] @keyword.conditional
[
  "continue" "while" "break" "for" "do" "in" "of"
] @keyword.repeat
[
  "return" "await" "yield"
] @keyword.return
[
  "finally" "catch" "throw" "try"
] @keyword.exception
[
  "instanceof" "satisfies" "asserts" "typeof" "delete" "keyof" "infer" "void"
  "new" "as" "is"
] @keyword.operator
"symbol" @type.builtin
[
  "undefined" "false" "true" "null"
] @constant.builtin
[
  "super" "this"
] @variable.builtin
[
  ">>>=" "**=" "<<=" ">>=" "??=" "||=" "&&=" "==="
  "!==" ">>>" "+=" "-=" "*=" "/=" "%=" "&="
  "|=" "^=" "==" "!=" "<=" ">=" "||" "&&"
  "??" "**" "++" "--" "<<" ">>" "=" "<"
  ">" "+" "-" "*" "/" "%" "!" "~"
  "|" "&" "^"
] @operator
[
  "(" ")" "{" "}" "[" "]"
] @punctuation.bracket
[
  "..." "?." ";" "," "?" ":"
] @punctuation.delimiter
