;; -----------------------------------------------------------------
;; Tree-sitter highlight queries generated by monogram.
;; Capture names follow the standard tree-sitter highlight vocabulary
;; (@keyword, @function, @type, @string, @property, @operator, …).
;; Inferred from rule SHAPES + the grammar's `scopes` section — the same
;; structural inference the TextMate generator uses.
;; -----------------------------------------------------------------

;; Bare identifier (lowest priority; specific patterns below win).
(ident) @variable

;; Declaration names (via the `name` field) → @function / @type.
(expr name: (ident) @type)
(expr name: (ident) @function)
(decl name: (ident) @function)
(decl name: (ident) @type)

;; Declaration names, keyword-anchored (disambiguates shared decl rules).
(expr "class" (ident) @type)
(expr "function" (ident) @function)
(decl "function" (ident) @function)
(decl "class" (ident) @type)

;; Structural member / type-param / property-access captures.
(member_name (ident) @property)
(expr (expr) (ident) @property)
(binding_property (ident) @property (binding_element))

;; Literal token nodes.
(shebang) @comment
(jsdoc) @comment.documentation
(triple_slash) @comment
(line_comment) @comment
(block_comment) @comment
(hex_number) @number
(octal_number) @number
(binary_number) @number
(big_int) @number
(number) @number
(string) @string
(template_chars) @string
(regex_literal) @string.regexp
(decorator) @function.macro
(private_field) @property
(template "`") @string
(template_substitution "${") @punctuation.special
(template_substitution "}") @punctuation.special

;; Well-known property names.
((ident) @property.builtin
  (#any-of? @property.builtin "length" "prototype" "constructor"))

;; Builtin / global / constant identifier names.
((ident) @variable.builtin
  (#any-of? @variable.builtin "console" "window" "document" "process" "module" "require" "exports" "global" "globalThis"))

;; Keyword, operator, and punctuation literals.
[
  "debugger" "accessor" "extends" "static" "const" "using" "class" "async"
  "with" "meta" "let" "var" "get" "set" "as"
] @keyword
[
  "constructor" "function" "=>"
] @keyword.function
[
  "import" "export" "from"
] @keyword.import
[
  "default" "switch" "else" "case" "if"
] @keyword.conditional
[
  "while" "for" "do" "in" "of"
] @keyword.repeat
[
  "continue" "return" "break" "await" "yield"
] @keyword.return
[
  "finally" "catch" "throw" "try"
] @keyword.exception
[
  "instanceof" "delete" "typeof" "void" "new"
] @keyword.operator
[
  "undefined" "false" "true" "null"
] @constant.builtin
[
  "super" "this"
] @variable.builtin
[
  ">>>=" "**=" "<<=" ">>=" "??=" "||=" "&&=" "==="
  "!==" ">>>" "+=" "-=" "*=" "/=" "%=" "&="
  "|=" "^=" "==" "!=" "||" "&&" "??" "**"
  "++" "--" "<<" ">>" "<=" ">=" "=" "+"
  "-" "*" "/" "%" "!" "~" "|" "&"
  "^" "<" ">"
] @operator
[
  "(" ")" "{" "}" "[" "]"
] @punctuation.bracket
[
  "..." "?." ";" "," "?" ":"
] @punctuation.delimiter
