/**
 * @file Tree-sitter grammar generated by monogram from a single CstGrammar.
 * @license MIT
 *
 * GENERATED — do not edit by hand. Regenerate from the source grammar.
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

module.exports = grammar({
  name: "yaml",

  extras: $ => [
    /\s/,
    $.comment
  ],

  rules: {
    stream: $ => seq(repeat(seq($.directive, optional($.newline))), optional($.indent), optional($.node), optional($.dedent), repeat(seq(optional($.newline), optional($.doc_end), optional($.newline), $.doc_start, optional($.newline), repeat(seq($.directive, optional($.newline))), optional($.indent), optional($.node), optional($.dedent))), optional($.newline), optional($.doc_end), optional($.newline)),

    node: $ => seq(optional($.anchor), optional($.tag), choice($.block_sequence, $.explicit_mapping, $.flow_mapping, $.flow_sequence, $.alias, $.mapping_or_scalar)),

    mapping_or_scalar: $ => seq($.scalar, optional(seq(":", optional($.map_value), repeat(seq($.newline, $.map_entry))))),

    map_entry: $ => choice(seq($.scalar, ":", optional($.map_value)), seq("?", optional($.map_value), optional($.newline), optional(seq(":", optional($.map_value))))),

    explicit_mapping: $ => seq("?", optional($.map_value), optional($.newline), optional(seq(":", optional($.map_value))), repeat(seq($.newline, $.map_entry))),

    value: $ => choice(seq($.indent, $.node, $.dedent), $.node),

    map_value: $ => choice(seq($.indent, $.node, $.dedent), $.inline_node),

    inline_node: $ => seq(optional($.anchor), optional($.tag), choice($.flow_mapping, $.flow_sequence, $.alias, $.mapping_or_scalar)),

    block_sequence: $ => seq($.seq_item, repeat(seq($.newline, $.seq_item))),

    seq_item: $ => seq("-", optional($.value)),

    flow_mapping: $ => seq("{", optional(seq($.flow_entry, repeat(seq(",", $.flow_entry)))), optional(","), "}"),

    flow_entry: $ => seq($.flow_scalar_or_node, optional(seq(":", $.flow_value))),

    flow_value: $ => choice($.flow_mapping, $.flow_sequence, $.alias, $.scalar),

    flow_scalar_or_node: $ => choice($.flow_mapping, $.flow_sequence, $.alias, $.scalar),

    flow_sequence: $ => seq("[", optional(seq($.flow_value, repeat(seq(",", $.flow_value)))), optional(","), "]"),

    scalar: $ => choice($.dquote_key, $.squote_key, $.dquote, $.squote, $.block_scalar, $.key, $.num, $.bool_null, $.plain),

    doc_start: $ => token(/---/),

    doc_end: $ => token(/\.\.\./),

    directive: $ => token(/%(?:[^\n#]|#)*/),

    comment: $ => token(/#[^\n]*/),

    dquote_key: $ => token(/"(?:\\.|[^"\\])*"/),

    squote_key: $ => token(/'(?:''|[^'])*'/),

    dquote: $ => token(/"(?:\\.|[^"\\])*"/),

    squote: $ => token(/'(?:''|[^'])*'/),

    anchor: $ => token(/&[^\s\[\]{},]+/),

    alias: $ => token(/\*[^\s\[\]{},]+/),

    tag: $ => token(/!(?:<[^>]*>|[^\s\[\]{},]*)/),

    block_scalar: $ => token(//),

    key: $ => token(/(?:[^\s\-?:,\[\]{}#&*!|>'"%@\`]|[-?:])(?:[^:#\n,\[\]{}]|:|#)*/),

    num: $ => token(/(?:[+-]?\.(?:inf|Inf|INF)|\.(?:nan|NaN|NAN)|0x[0-9a-fA-F]+|0o[0-7]+|[+-]?(?:\.[0-9]+|[0-9]+(?:\.[0-9]*)?)(?:[eE][+-]?[0-9]+)?)/),

    bool_null: $ => token(/(?:true|True|TRUE|false|False|FALSE|null|Null|NULL|~)/),

    plain: $ => token(/(?:[^\s\-?:,\[\]{}#&*!|>'"%@\`]|[-?:])(?:[^:#\n,\[\]{}]|:|#)*/),

    indent: $ => token(//),

    dedent: $ => token(//),

    newline: $ => token(//)
  }
});

// entry rule: stream
