/**
 * @file Tree-sitter grammar generated by monogram from a single CstGrammar.
 * @license MIT
 *
 * GENERATED — do not edit by hand. Regenerate from the source grammar.
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

module.exports = grammar({
  name: "yaml",

  extras: $ => [
    /\s/,
    $.comment
  ],

  externals: $ => [
    $.indent,
    $.dedent,
    $.newline,
    $.block_scalar
  ],

  conflicts: $ => [
    [$.stream, $.node],
    [$.empty_key_mapping],
    [$.explicit_entry],
    [$.next_doc],
    [$.stream, $.next_doc],
    [$.node],
    [$.key, $.plain],
    [$.scalar, $.doc_fold],
    [$.explicit_mapping],
    [$.block_sequence],
    [$.map_value_scalar, $.map_value_node_scalar],
    [$.scalar, $.block_key_scalar],
    [$.map_value, $.map_value_node],
    [$.flow_explicit],
    [$.flow_mapping],
    [$.flow_sequence],
    [$.explicit_doc_body],
    [$.inline_doc_node],
    [$.alias_or_keyed],
    [$.doc_fold],
    [$.mapping_from_flow],
    [$.mapping_or_scalar],
    [$.property, $.node],
    [$.seq_item],
    [$.property],
    [$.flow_node],
    [$.node, $.explicit_doc_body],
    [$.node, $.after_doc_end],
    [$.after_doc_end],
    [$.map_entry],
    [$.stream, $.explicit_doc_body],
    [$.map_entry_no_empty],
    [$.seq_value_node],
    [$.mapping_or_scalar, $.doc_fold],
    [$.map_value_scalar, $.map_inline_scalar],
    [$.content_node, $.mapping_from_flow],
    [$.mapping_or_scalar, $.map_value],
  ],

  rules: {
    stream: $ => choice(seq(repeat1(seq(choice($.yaml_directive, $.directive), optional($.newline))), optional(seq($.doc_start, optional($.explicit_doc_body), repeat(seq(optional($.newline), $.next_doc)), optional($.newline), optional($.doc_end), optional($.newline)))), seq(optional($.indent), optional(choice($.doc_fold, optional($.node))), optional($.dedent), repeat(seq(optional($.newline), $.next_doc)), optional($.newline), optional($.doc_end), optional($.newline))),

    property: $ => choice(seq($.anchor, optional($.tag)), seq($.tag, optional($.anchor))),

    content_node: $ => choice($.block_sequence, $.explicit_mapping, $.empty_key_mapping, $.flow_mapping, $.flow_sequence, $.mapping_from_flow, $.alias_or_keyed, $.mapping_or_scalar),

    node: $ => choice(choice(seq($.anchor, optional($.tag), optional(choice(seq($.indent, optional($.node), $.dedent), seq($.newline, optional($.node)), $.block_sequence, $.explicit_mapping, $.empty_key_mapping, $.mapping_from_flow, $.flow_mapping, $.flow_sequence, $.alias_or_keyed, $.mapping_or_scalar))), seq($.tag, optional(choice(seq($.indent, optional($.node), $.dedent), seq($.newline, optional($.node)), $.block_sequence, $.explicit_mapping, $.empty_key_mapping, $.mapping_from_flow, $.flow_mapping, $.flow_sequence, $.alias_or_keyed, $.mapping_or_scalar))), choice(seq($.indent, optional($.node), $.dedent), seq($.newline, optional($.node)), $.block_sequence, $.explicit_mapping, $.empty_key_mapping, $.mapping_from_flow, $.flow_mapping, $.flow_sequence, $.alias_or_keyed, $.mapping_or_scalar)), seq($.tag, $.anchor, optional(choice(seq($.indent, optional($.node), $.dedent), seq($.newline, optional($.node)), $.block_sequence, $.explicit_mapping, $.empty_key_mapping, $.mapping_from_flow, $.flow_mapping, $.flow_sequence, $.alias_or_keyed, $.mapping_or_scalar))), $.block_sequence),

    mapping_or_scalar: $ => choice(seq(choice($.num, $.bool_null, $.plain), $.indent, choice($.num, $.bool_null, $.plain), repeat(seq($.newline, choice($.num, $.bool_null, $.plain))), $.dedent), seq($.block_key_scalar, ":", optional($.map_value_scalar), repeat(seq($.newline, $.map_entry))), $.scalar),

    alias_or_keyed: $ => seq($.alias, optional(seq(":", optional($.map_value_scalar), repeat(seq($.newline, $.map_entry))))),

    block_key: $ => choice(seq(optional($.property), $.block_key_scalar), $.alias, seq(optional($.property), choice($.flow_mapping, $.flow_sequence))),

    explicit_entry: $ => seq("?", optional($.map_value), optional(choice(seq($.newline, ":", optional($.map_value)), seq(":", optional($.map_value))))),

    map_entry: $ => choice(seq($.block_key, ":", optional($.map_value_scalar)), $.explicit_entry, seq(":", optional($.map_value_scalar))),

    map_entry_no_empty: $ => choice(seq($.block_key, ":", optional($.map_value_scalar)), $.explicit_entry),

    explicit_mapping: $ => seq($.explicit_entry, repeat(seq($.newline, $.map_entry))),

    empty_key_mapping: $ => seq(":", optional($.map_value_scalar), repeat(seq($.newline, $.map_entry_no_empty))),

    value: $ => choice(seq($.indent, choice($.num, $.bool_null, $.plain), repeat1(seq($.newline, $.plain)), $.dedent), seq($.indent, optional($.node), $.dedent), $.seq_value_node),

    map_value: $ => choice(seq(choice($.num, $.bool_null, $.plain), $.indent, choice($.num, $.bool_null, $.plain), repeat(seq($.newline, choice($.num, $.bool_null, $.plain))), $.dedent), seq($.indent, choice($.num, $.bool_null, $.plain), repeat1(seq($.newline, $.plain)), $.dedent), seq($.indent, optional($.node), $.dedent), seq($.indent, $.property, $.dedent, $.content_node), seq($.indent, $.property, $.dedent, $.newline, $.block_sequence), seq($.property, $.newline, $.block_sequence), seq($.newline, $.block_sequence), $.map_value_node),

    map_value_scalar: $ => choice(seq(choice($.num, $.bool_null, $.plain), $.indent, choice($.num, $.bool_null, $.plain), repeat(seq($.newline, choice($.num, $.bool_null, $.plain))), $.dedent), seq($.indent, choice($.num, $.bool_null, $.plain), repeat1(seq($.newline, $.plain)), $.dedent), seq($.indent, optional($.node), $.dedent), seq($.indent, $.property, $.dedent, $.content_node), seq($.indent, $.property, $.dedent, $.newline, $.block_sequence), seq($.property, $.newline, $.block_sequence), seq($.newline, $.block_sequence), $.map_value_node_scalar),

    indented_value_node: $ => choice(seq($.property, choice(seq($.indent, $.indented_value_node, $.dedent), $.collection_content)), $.content_node),

    collection_content: $ => choice($.block_sequence, $.explicit_mapping, $.flow_mapping, $.flow_sequence, $.mapping_from_flow, $.mapping_from_scalar),

    mapping_from_scalar: $ => seq($.block_key_scalar, ":", optional($.map_value_scalar), repeat(seq($.newline, $.map_entry))),

    mapping_from_flow: $ => seq(choice($.flow_mapping, $.flow_sequence), ":", optional($.map_value_scalar), repeat(seq($.newline, $.map_entry))),

    map_value_node: $ => choice(seq($.property, optional(choice(seq($.indent, $.indented_value_node, $.dedent), $.map_inline_content))), $.map_inline_content),

    map_inline_content: $ => choice($.flow_mapping, $.flow_sequence, $.alias, $.mapping_or_scalar),

    map_value_node_scalar: $ => choice(seq($.property, optional(choice(seq($.indent, $.indented_value_node, $.dedent), $.map_inline_scalar))), $.map_inline_scalar),

    map_inline_scalar: $ => choice($.flow_mapping, $.flow_sequence, $.alias, seq(choice($.num, $.bool_null, $.plain), $.indent, choice($.num, $.bool_null, $.plain), repeat(seq($.newline, choice($.num, $.bool_null, $.plain))), $.dedent), $.scalar),

    seq_value_node: $ => choice(seq($.property, optional(choice(seq($.indent, $.indented_value_node, $.dedent), $.seq_inline_content))), $.seq_inline_content),

    seq_inline_content: $ => choice($.block_sequence, $.empty_key_mapping, $.flow_mapping, $.flow_sequence, $.alias, $.mapping_or_scalar),

    block_sequence: $ => seq($.seq_item, repeat(seq($.newline, $.seq_item))),

    seq_item: $ => seq("-", optional($.value)),

    flow_node: $ => choice(seq($.property, optional(choice($.flow_mapping, $.flow_sequence, $.alias, $.scalar))), choice($.flow_mapping, $.flow_sequence, $.alias, $.scalar)),

    flow_explicit: $ => seq("?", optional(optional($.flow_node))),

    flow_map_entry: $ => choice(seq($.flow_explicit, optional(optional($.flow_node)), optional(seq(":", optional(optional($.flow_node))))), seq($.flow_node, optional(seq(":", optional(optional($.flow_node))))), seq(":", optional(optional($.flow_node)))),

    flow_mapping: $ => seq("{", optional(seq(optional($.flow_map_entry), repeat(seq(",", optional($.flow_map_entry))))), optional(","), "}"),

    flow_seq_entry: $ => choice(seq($.flow_seq_key, ":", optional(optional($.flow_node))), seq("?", optional(optional($.flow_node)), optional(seq(":", optional(optional($.flow_node))))), seq(":", optional(optional($.flow_node))), $.flow_node),

    flow_seq_key: $ => choice(seq(optional($.property), choice($.flow_mapping, $.flow_sequence, $.dquote_key, $.squote_key, $.key)), $.alias),

    flow_sequence: $ => seq("[", optional(seq(optional($.flow_seq_entry), repeat(seq(",", optional($.flow_seq_entry))))), optional(","), "]"),

    scalar: $ => choice($.dquote_key, $.squote_key, $.dquote, $.squote, $.block_scalar, $.key, $.num, $.bool_null, $.plain),

    block_key_scalar: $ => choice($.dquote_key, $.squote_key, $.key, $.num, $.bool_null, $.plain),

    doc_fold: $ => seq(choice($.num, $.bool_null, $.plain), repeat1(choice(seq($.newline, choice($.plain, $.yaml_directive, $.directive)), seq($.indent, choice($.plain, $.yaml_directive, $.directive), repeat(seq($.newline, choice($.plain, $.yaml_directive, $.directive))), $.dedent)))),

    inline_doc_node: $ => choice(seq($.property, optional(choice(seq($.indent, $.doc_fold, $.dedent), seq($.indent, optional($.node), $.dedent), seq($.newline, $.doc_fold), seq($.newline, optional($.node)), $.flow_mapping, $.flow_sequence, $.alias, $.scalar))), $.doc_fold, choice($.flow_mapping, $.flow_sequence, $.alias, $.scalar)),

    explicit_doc_body: $ => choice(seq($.newline, optional($.indent), optional(choice($.doc_fold, optional($.node))), optional($.dedent)), $.inline_doc_node),

    after_doc_end: $ => choice(seq(repeat(seq(choice($.yaml_directive, $.directive), optional($.newline))), $.doc_start, optional($.explicit_doc_body)), choice(seq($.indent, choice($.doc_fold, optional($.node)), optional($.dedent)), seq(choice($.doc_fold, $.node), optional($.dedent)), $.dedent)),

    next_doc: $ => choice(seq($.doc_start, optional($.explicit_doc_body)), seq($.doc_end, optional(seq($.newline, optional(optional($.after_doc_end)))))),

    doc_start: $ => token(/---/),

    doc_end: $ => token(/\.\.\./),

    yaml_directive: $ => token(/%YAML[ \t]+[0-9]+\.[0-9]+/),

    directive: $ => token(/%(?:[^\n#]|#)*/),

    comment: $ => token(/#[^\n]*/),

    dquote_key: $ => token(/"(?:\\(?:[0abtnvfre"\/\\N_LP \t]|x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})|[^"\\\r\n])*"/),

    squote_key: $ => token(/'(?:''|[^'\r\n])*'/),

    dquote: $ => token(/"(?:\\(?:[0abtnvfre"\/\\N_LP \t]|x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8}|\r?\n)|[^"\\])*"/),

    squote: $ => token(/'(?:''|[^'])*'/),

    anchor: $ => token(/&[^\t\n\f\r \[\]{},]+/),

    alias: $ => token(/\*[^\t\n\f\r \[\]{},]+/),

    tag: $ => token(/!(?:<[^>]*>|[^\t\n\f\r \[\]{},]*)/),

    key: $ => token(/(?:[^\t\n\f\r \-?:,\[\]{}#&*!|>'"%@`]|[\-?:])(?:[^:#\n,\[\]{}]|:|#)*/),

    num: $ => token(/(?:[+\-]?\.(?:inf|Inf|INF)|\.(?:nan|NaN|NAN)|0x[0-9A-Fa-f]+|0o[0-7]+|[+\-]?(?:\.[0-9]+|[0-9]+(?:\.[0-9]*)?)(?:[eE][+\-]?[0-9]+)?)/),

    bool_null: $ => token(/(?:true|True|TRUE|false|False|FALSE|null|Null|NULL|~)/),

    plain: $ => token(/(?:[^\t\n\f\r \-?:,\[\]{}#&*!|>'"%@`]|[\-?:])(?:[^:#\n,\[\]{}]|:|#)*/)
  }
});

// entry rule: stream
