// Tree-sitter external scanner generated by monogram.
//
// PARTIAL IMPLEMENTATION — the regex-literal scan is wired from the
// grammar's `regexContext` hint; the template-interpolation machinery is
// stubbed (delimiters are filled in, the state machine is a TODO).
//
// All language-specific data below is DERIVED from the CstGrammar, not
// hardcoded: the division-after character sets, the regex flag chars, and
// the template delimiters all come from the grammar's token hints.

#include "tree_sitter/parser.h"
#include <string.h>
#include <wctype.h>

enum TokenType {
  REGEX_LITERAL,
};

// Scanner state: depth of nested `{` inside each open template
// interpolation hole, mirroring the JS lexer's templateStack. Kept tiny
// and trivially (de)serializable.
typedef struct {
  uint8_t interp_depth_stack[32];
  uint8_t interp_stack_len;
} Scanner;

void *tree_sitter_typescript_external_scanner_create(void) {
  Scanner *s = ts_malloc(sizeof(Scanner));
  s->interp_stack_len = 0;
  return s;
}

void tree_sitter_typescript_external_scanner_destroy(void *payload) {
  ts_free(payload);
}

unsigned tree_sitter_typescript_external_scanner_serialize(void *payload, char *buffer) {
  Scanner *s = (Scanner *)payload;
  unsigned len = 0;
  buffer[len++] = (char)s->interp_stack_len;
  for (unsigned i = 0; i < s->interp_stack_len; i++) buffer[len++] = (char)s->interp_depth_stack[i];
  return len;
}

void tree_sitter_typescript_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
  Scanner *s = (Scanner *)payload;
  s->interp_stack_len = 0;
  if (length > 0) {
    s->interp_stack_len = (uint8_t)buffer[0];
    for (unsigned i = 0; i < s->interp_stack_len && i + 1 < length; i++) s->interp_depth_stack[i] = (uint8_t)buffer[i + 1];
  }
}

static inline void advance(TSLexer *lexer) { lexer->advance(lexer, false); }
static inline void skip(TSLexer *lexer) { lexer->advance(lexer, true); }

// ── Regex-literal scan ──────────────────────────────────────────
// `/` is a regex literal ONLY in expression-start position. tree-sitter
// gives us `valid_symbols`: it asks for the regex token exactly where the
// grammar permits it (i.e. NOT after a value/`)`/`]`), so the bulk of the
// regex-vs-division decision is already made by the LR context. We only
// need to scan the literal body here.
//
// Regex flag characters (derived from the token pattern): "gimsuydv"
// Division-after texts (informational; LR ctx handles these): ) ] ++ -- this super true false null undefined
// Regex-after keywords (informational): in of instanceof typeof delete void await yield throw return case do else new
static bool scan_regex(TSLexer *lexer) {
  if (lexer->lookahead != '/') return false;
  advance(lexer); // consume opening /
  // Empty regex `//` is actually a comment — bail so the lexer matches that.
  if (lexer->lookahead == '/' || lexer->lookahead == '*') return false;
  bool in_class = false;
  for (;;) {
    int32_t c = lexer->lookahead;
    if (c == 0 || c == '\n') return false; // unterminated
    if (c == '\\') { advance(lexer); if (lexer->lookahead == 0) return false; advance(lexer); continue; }
    if (c == '[') { in_class = true; advance(lexer); continue; }
    if (c == ']') { in_class = false; advance(lexer); continue; }
    if (c == '/' && !in_class) { advance(lexer); break; }
    advance(lexer);
  }
  // Trailing flag characters.
  const char *flags = "gimsuydv";
  while (lexer->lookahead != 0 && strchr(flags, (char)lexer->lookahead) != NULL) advance(lexer);
  lexer->result_symbol = REGEX_LITERAL;
  lexer->mark_end(lexer);
  return true;
}

bool tree_sitter_typescript_external_scanner_scan(void *payload, TSLexer *lexer,
                                                          const bool *valid_symbols) {
  Scanner *s = (Scanner *)payload;
  (void)s;

  // Skip leading whitespace (the regular lexer normally does this, but the
  // external scanner runs first when any external symbol is valid).
  while (iswspace(lexer->lookahead)) skip(lexer);

  if (valid_symbols[REGEX_LITERAL] && lexer->lookahead == '/') {
    if (scan_regex(lexer)) return true;
  }

  // ── TEMPLATE INTERPOLATION (TODO — STUB) ─────────────────────────
  // Template delimiters (derived from the grammar's template hint):
  //   open        = "`"
  //   interpOpen  = "${"
  //   interpClose = "}"
  //
  // A full implementation tracks `{`-nesting inside each open hole using
  // s->interp_depth_stack (mirroring gen-lexer.ts's templateStack) and emits
  // template-head / template-middle / template-tail tokens so `${ … }` holes
  // re-enter the expression grammar. Not implemented here.
  //
  // NOTE: this scaffold treats the whole template as a single token via the
  // regex rule in grammar.js, so simple (non-interpolated) templates already
  // highlight; interpolation holes are NOT yet re-parsed as expressions.

  return false;
}
