; AUTO-GENERATED by src/gen-treesitter.ts (markup path) — do not edit by hand.
(tag_name) @tag
(attribute_name) @attribute
(quoted_attribute_value) @string
(attribute_value) @string
(comment) @comment
"<" @punctuation.bracket
">" @punctuation.bracket
"</" @punctuation.bracket
"/>" @punctuation.bracket
"=" @punctuation.delimiter
