/**
 * @file Tree-sitter grammar generated by monogram from a single CstGrammar.
 * @license MIT
 *
 * GENERATED — do not edit by hand. Regenerate from the source grammar.
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

module.exports = grammar({
  name: "javascript",

  extras: $ => [
    /\s/,
    $.shebang,
    $.jsdoc,
    $.triple_slash,
    $.line_comment,
    $.block_comment
  ],

  word: $ => $.ident,

  externals: $ => [
    $.regex_literal,
    $.template_chars
  ],

  conflicts: $ => [
    [$.expr],
    [$.stmt],
    [$.stmt, $.decl],
    [$.expr, $.decl],
    [$.program, $.stmt],
    [$.expr, $.param],
    [$.expr, $.new_target],
    [$.expr, $.block],
    [$.expr, $.member_name],
    [$.expr, $.prop],
    [$.member_name, $.stmt],
    [$.decl],
    [$.binding],
    [$.expr, $.binding_pattern],
    [$.expr, $.binding_element],
    [$.prop, $.binding_property],
    [$.member_name, $.binding_property],
    [$.expr, $.block, $.decl],
    [$.expr, $.prop, $.import_specifier],
    [$.expr, $.import_specifier],
    [$.expr, $.array_binding_element],
    [$.expr, $.binding_property],
    [$.prop, $.member_name],
    [$.prop, $.member_name, $.binding_property],
    [$.stmt, $.param],
    [$.class_member],
    [$.expr, $.prop, $.export_specifier],
    [$.expr, $.export_specifier],
    [$.prop],
    [$.prop, $.decl],
    [$.expr, $.prop, $.member_name],
    [$.decorator_expr, $.new_target],
    [$.binding_element],
  ],

  rules: {
    program: $ => repeat(choice($.decl, $.stmt)),

    decorator_expr: $ => seq($.decorator, optional(seq("(", optional(seq($.expr, repeat(seq(",", $.expr)), optional(","))), ")"))),

    expr: $ => choice(
      prec.right(1, seq($.expr, field('operator', choice("=", "+=", "-=", "*=", "/=", "%=", "**=", "<<=", ">>=", ">>>=", "&=", "|=", "^=")), $.expr)),
      prec.right(2, seq($.expr, field('operator', choice("??=", "||=", "&&=")), $.expr)),
      prec.left(3, seq($.expr, field('operator', "??"), $.expr)),
      prec.left(4, seq($.expr, field('operator', "||"), $.expr)),
      prec.left(5, seq($.expr, field('operator', "&&"), $.expr)),
      prec.left(6, seq($.expr, field('operator', "|"), $.expr)),
      prec.left(7, seq($.expr, field('operator', "^"), $.expr)),
      prec.left(8, seq($.expr, field('operator', "&"), $.expr)),
      prec(9, seq($.expr, field('operator', choice("==", "!=", "===", "!==")), $.expr)),
      prec(10, seq($.expr, field('operator', choice("<", ">", "<=", ">=")), $.expr)),
      prec.left(11, seq($.expr, field('operator', choice("<<", ">>", ">>>")), $.expr)),
      prec.left(12, seq($.expr, field('operator', choice("+", "-")), $.expr)),
      prec.left(13, seq($.expr, field('operator', choice("*", "/", "%")), $.expr)),
      prec.right(14, seq($.expr, field('operator', "**"), $.expr)),
      prec.right(15, seq(field('operator', choice("!", "~", "+", "-", "typeof", "void", "delete", "await", "yield")), $.expr)),
      prec.right(16, seq(field('operator', choice("++", "--")), $.expr)),
      prec.left(17, seq($.expr, field('operator', choice("++", "--")))),
      "true",
      "false",
      "null",
      "undefined",
      "this",
      "super",
      $.ident,
      $.number,
      $.string,
      $.template,
      $.regex_literal,
      seq("...", $.expr),
      prec.left(18, seq($.expr, "(", optional(seq($.expr, repeat(seq(",", $.expr)), optional(","))), ")")),
      prec.left(18, seq($.expr, ".", choice($.ident, $.private_field))),
      prec.left(18, seq($.expr, "?.", choice($.ident, $.private_field, seq("(", optional(seq($.expr, repeat(seq(",", $.expr)), optional(","))), ")"), seq("[", $.expr, "]"), $.template))),
      prec.left(18, seq($.expr, "[", $.expr, "]")),
      prec.left(18, seq($.expr, "?", $.expr, ":", $.expr)),
      prec.left(18, seq($.expr, "instanceof", $.expr)),
      prec.left(18, seq($.expr, "in", $.expr)),
      prec.left(18, seq($.expr, $.template)),
      seq("new", $.new_target, optional(seq("(", optional(seq($.expr, repeat(seq(",", $.expr)), optional(","))), ")"))),
      seq("new", "class", field('name', $.ident), optional(seq("extends", $.class_heritage)), "{", repeat($.class_member), "}", optional(seq("(", optional(seq($.expr, repeat(seq(",", $.expr)), optional(","))), ")"))),
      seq("new", "class", optional(seq("extends", $.class_heritage)), "{", repeat($.class_member), "}", optional(seq("(", optional(seq($.expr, repeat(seq(",", $.expr)), optional(","))), ")"))),
      seq("[", repeat(seq(optional($.expr), ",")), optional($.expr), "]"),
      seq("{", optional(seq($.prop, repeat(seq(",", $.prop)), optional(","))), "}"),
      seq(optional("async"), "(", optional(seq($.param, repeat(seq(",", $.param)), optional(","))), ")", "=>", choice($.expr, $.block)),
      seq("async", $.ident, "=>", choice($.expr, $.block)),
      seq($.ident, "=>", choice($.expr, $.block)),
      seq("yield", choice(seq("*", $.expr), optional($.expr))),
      seq("(", $.expr, repeat(seq(",", $.expr)), ")"),
      seq("import", choice(seq("(", $.expr, ")"), seq(".", "meta"))),
      $.private_field,
      $.hex_number,
      $.octal_number,
      $.binary_number,
      $.big_int,
      seq(optional("async"), "function", optional("*"), optional(field('name', $.ident)), "(", optional(seq($.param, repeat(seq(",", $.param)), optional(","))), ")", $.block),
      seq(optional($.decorator_expr), "class", field('name', $.ident), repeat(seq("extends", optional(seq(choice($.class_heritage), repeat(seq(",", choice($.class_heritage))), optional(","))))), "{", repeat($.class_member), "}"),
      seq(optional($.decorator_expr), "class", repeat(seq("extends", optional(seq(choice($.class_heritage), repeat(seq(",", choice($.class_heritage))), optional(","))))), "{", repeat($.class_member), "}")
    ),

    prop: $ => choice(seq("...", $.expr), seq(choice("get", "set"), $.member_name, "(", optional(optional(seq($.param, repeat(seq(",", $.param)), optional(",")))), ")", $.block), seq(optional("async"), optional("*"), $.member_name, "(", optional(seq($.param, repeat(seq(",", $.param)), optional(","))), ")", $.block), seq($.member_name, ":", $.expr), seq("[", $.expr, repeat(seq(",", $.expr)), "]", ":", $.expr), seq($.ident, choice(seq("=", $.expr), blank()))),

    member_name: $ => choice($.ident, $.private_field, $.string, $.number, $.hex_number, $.octal_number, $.binary_number, $.big_int, seq("[", $.expr, "]")),

    new_target: $ => choice($.ident, seq($.new_target, ".", $.ident), seq($.new_target, "[", $.expr, "]"), seq("(", $.expr, ")")),

    class_heritage: $ => choice($.ident, $.number, $.string, "true", "false", "null", "undefined", seq($.class_heritage, ".", $.ident), seq($.class_heritage, "(", optional(seq($.expr, repeat(seq(",", $.expr)), optional(","))), ")")),

    stmt: $ => choice($.block, seq(choice("let", "const", "var"), optional(seq($.binding, repeat(seq(",", $.binding)), optional(","))), optional(";")), seq("if", "(", $.expr, repeat(seq(",", $.expr)), ")", $.stmt, optional(seq("else", $.stmt))), seq("for", optional("await"), "(", $.for_head, ")", $.stmt), seq("while", "(", $.expr, repeat(seq(",", $.expr)), ")", $.stmt), seq("do", $.stmt, "while", "(", $.expr, repeat(seq(",", $.expr)), ")", optional(";")), seq("switch", "(", $.expr, repeat(seq(",", $.expr)), ")", "{", repeat($.switch_case), "}"), seq("return", optional(seq($.expr, repeat(seq(",", $.expr)))), optional(";")), seq("throw", $.expr, repeat(seq(",", $.expr)), optional(";")), seq("break", optional($.ident), optional(";")), seq("continue", optional($.ident), optional(";")), seq("try", $.block, optional(seq("catch", optional(seq("(", choice($.param, $.binding_pattern), ")")), $.block)), optional(seq("finally", $.block))), seq($.ident, ":", $.stmt), ";", seq("debugger", optional(";")), seq("with", "(", $.expr, ")", $.stmt), seq(optional("await"), "using", optional(seq($.binding, repeat(seq(",", $.binding)), optional(","))), optional(";")), $.decl, seq($.expr, repeat(seq(",", $.expr)), optional(";"))),

    block: $ => seq("{", repeat($.stmt), "}"),

    binding_property: $ => choice(seq($.ident, ":", $.binding_element), seq($.ident, optional(seq("=", $.expr))), seq(choice($.string, $.number, seq("[", $.expr, "]")), ":", $.binding_element), seq("...", choice($.ident, $.binding_pattern))),

    binding_element: $ => seq(choice($.ident, $.binding_pattern), optional(seq("=", $.expr))),

    array_binding_element: $ => choice($.binding_element, seq("...", choice($.ident, $.binding_pattern))),

    binding_pattern: $ => choice(seq("{", optional(seq($.binding_property, repeat(seq(",", $.binding_property)), optional(","))), "}"), seq("[", optional($.array_binding_element), repeat(seq(",", optional($.array_binding_element))), "]")),

    binding: $ => seq(choice($.ident, $.binding_pattern), optional(seq("=", $.expr))),

    for_binding: $ => seq(choice($.ident, $.binding_pattern), optional(seq("=", $.expr))),

    param: $ => seq(optional($.decorator_expr), choice(seq($.ident, optional(seq("=", $.expr))), seq($.binding_pattern, optional(seq("=", $.expr))), seq("...", choice($.ident, $.binding_pattern), optional(seq("=", $.expr))))),

    for_head: $ => choice(seq(choice("let", "const", "var", "using", seq("await", "using")), optional(seq($.for_binding, repeat(seq(",", $.for_binding)), optional(","))), choice(seq(";", optional(seq($.expr, repeat(seq(",", $.expr)))), ";", optional(seq($.expr, repeat(seq(",", $.expr))))), seq("in", $.expr, repeat(seq(",", $.expr))), seq("of", $.expr))), seq(optional(seq($.expr, repeat(seq(",", $.expr)))), ";", optional(seq($.expr, repeat(seq(",", $.expr)))), ";", optional(seq($.expr, repeat(seq(",", $.expr))))), seq($.expr, "in", $.expr, repeat(seq(",", $.expr))), seq($.expr, "of", $.expr)),

    switch_case: $ => choice(seq("case", $.expr, repeat(seq(",", $.expr)), ":"), seq("default", ":"), $.stmt),

    decl: $ => choice(seq(optional("async"), "function", optional("*"), field('name', $.ident), "(", optional(seq($.param, repeat(seq(",", $.param)), optional(","))), ")", $.block), seq(repeat($.decorator_expr), "class", field('name', $.ident), repeat(seq("extends", optional(seq(choice($.class_heritage), repeat(seq(",", choice($.class_heritage))), optional(","))))), "{", repeat($.class_member), "}"), seq("export", choice($.decl, $.stmt)), seq(repeat1($.decorator_expr), $.decl), seq("export", "default", choice(seq(optional("async"), "function", optional("*"), optional(field('name', $.ident)), "(", optional(seq($.param, repeat(seq(",", $.param)), optional(","))), ")", $.block), seq($.expr, optional(";")))), seq("export", "*", choice(seq("from", $.string, optional(";")), seq("as", $.ident, "from", $.string, optional(";")))), seq("export", "{", optional(seq($.export_specifier, repeat(seq(",", $.export_specifier)), optional(","))), "}", optional(seq("from", $.string)), optional(";")), seq("import", choice(seq($.import_clause, "from", $.string, optional(";")), seq($.ident, "=", $.expr, optional(";")), seq($.string, optional(";")))), seq(repeat($.decorator_expr), "export", choice($.decl, $.stmt))),

    class_member: $ => choice(";", $.decorator_expr, seq("constructor", "(", optional(seq($.param, repeat(seq(",", $.param)), optional(","))), ")", $.block, optional(";")), seq("static", $.block), seq(repeat(choice("static", "accessor", "async")), choice(seq("*", $.member_name, "(", optional(seq($.param, repeat(seq(",", $.param)), optional(","))), ")", optional($.block), optional(";")), seq(choice("get", "set"), $.member_name, "(", optional(optional(seq($.param, repeat(seq(",", $.param)), optional(",")))), ")", optional($.block), optional(";")), seq($.member_name, choice(seq("(", optional(seq($.param, repeat(seq(",", $.param)), optional(","))), ")", optional($.block), optional(";")), seq(optional(seq("=", $.expr)), optional(";")))))), seq($.member_name, optional(seq("=", $.expr)), optional(";")), seq($.member_name, "(", optional(seq($.param, repeat(seq(",", $.param)), optional(","))), ")", optional($.block), optional(";"))),

    import_clause: $ => choice(seq($.ident, optional(seq(",", choice(seq("{", optional(seq($.import_specifier, repeat(seq(",", $.import_specifier)), optional(","))), "}"), seq("*", "as", $.ident))))), seq("{", optional(seq($.import_specifier, repeat(seq(",", $.import_specifier)), optional(","))), "}"), seq("*", "as", $.ident)),

    import_specifier: $ => choice(seq($.ident, optional(seq("as", $.ident))), seq($.string, "as", $.ident)),

    export_specifier: $ => seq(choice($.ident, $.string), optional(seq("as", choice($.ident, $.string)))),

    shebang: $ => token(/#![^\n]*/),

    jsdoc: $ => token(/\/\*\*(?:[\s\S])*?\*\//),

    triple_slash: $ => token(/\/\/\/[ \t]*<[^\n]*/),

    line_comment: $ => token(/\/\/[^\n]*/),

    block_comment: $ => token(/\/\*(?:[\s\S])*?\*\//),

    ident: $ => token(/(?:[a-zA-Z_$]|\\u[0-9A-Fa-f]{4}|\\u\{[0-9A-Fa-f]+\})(?:[a-zA-Z0-9_$]|\\u[0-9A-Fa-f]{4}|\\u\{[0-9A-Fa-f]+\})*/),

    hex_number: $ => token(/0[xX][0-9A-Fa-f]+(?:_[0-9A-Fa-f]+)*n?/),

    octal_number: $ => token(/0[oO][0-7]+(?:_[0-7]+)*n?/),

    binary_number: $ => token(/0[bB][01]+(?:_[01]+)*n?/),

    big_int: $ => token(/[0-9]+(?:_[0-9]+)*n/),

    number: $ => token(/(?:[0-9]+(?:_[0-9]+)*(?:\.[0-9]*(?:_[0-9]+)*)?|\.[0-9]+(?:_[0-9]+)*)(?:[eE][+\-]?[0-9]+(?:_[0-9]+)*)?/),

    string: $ => token(/"(?:[^"\\]|\\(?:u\{0*(?:[0-9A-Fa-f]{1,5}|10[0-9A-Fa-f]{4})\}|u[0-9A-Fa-f]{4}|x[0-9A-Fa-f]{2}|[^ux]))*"|'(?:[^'\\]|\\(?:u\{0*(?:[0-9A-Fa-f]{1,5}|10[0-9A-Fa-f]{4})\}|u[0-9A-Fa-f]{4}|x[0-9A-Fa-f]{2}|[^ux]))*'/),

    decorator: $ => token(/@(?:(?:[a-zA-Z_$]|\\u[0-9A-Fa-f]{4}|\\u\{[0-9A-Fa-f]+\})(?:[a-zA-Z0-9_$]|\\u[0-9A-Fa-f]{4}|\\u\{[0-9A-Fa-f]+\}|\.)*)?/),

    private_field: $ => token(/#(?:[a-zA-Z_$]|\\u[0-9A-Fa-f]{4}|\\u\{[0-9A-Fa-f]+\})(?:[a-zA-Z0-9_$]|\\u[0-9A-Fa-f]{4}|\\u\{[0-9A-Fa-f]+\})*/),

    template: $ => seq(
      "`",
      repeat(choice($.template_chars, $.template_substitution)),
      "`"
    ),

    template_substitution: $ => seq("${", $.expr, "}")
  }
});

// entry rule: program
