// AUTO-GENERATED by src/gen-treesitter.ts (markup path) — do not edit by hand.
// v1: well-formed HTML structure (tags / attributes / text / comments). Raw-text
// element bodies (<script>/<style>) are treated as ordinary text — a literal '<'
// inside them is not yet supported (an external scanner is the next increment).
module.exports = grammar({
  name: 'html',
  extras: $ => [/\s+/],
  rules: {
    document: $ => repeat($._node),
    _node: $ => choice($.element, $.comment, $.text),
    element: $ => choice(
      $.void_element,
      $.self_closing_tag,
      seq($.start_tag, repeat($._node), $.end_tag),
    ),
    start_tag: $ => seq('<', $.tag_name, repeat($.attribute), '>'),
    end_tag: $ => seq('</', $.tag_name, '>'),
    self_closing_tag: $ => seq('<', $.tag_name, repeat($.attribute), '/>'),
    void_element: $ => seq('<', alias($._void_name, $.tag_name), repeat($.attribute), optional('/'), '>'),
    attribute: $ => seq($.attribute_name, optional(seq('=', choice($.quoted_attribute_value, $.attribute_value)))),
    attribute_name: $ => /[a-zA-Z][\w:.-]*/,
    attribute_value: $ => /[^\s"'<>=`]+/,
    quoted_attribute_value: $ => choice(seq('"', optional(/[^"]+/), '"'), seq("'", optional(/[^']+/), "'")),
    tag_name: $ => /[a-zA-Z][\w:.-]*/,
    _void_name: $ => token(prec(1, /(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)/i)),
    text: $ => /[^<]+/,
    comment: $ => token(seq('<!--', /[\s\S]*?/, '-->')),
  }
});
