// AUTO-GENERATED by src/gen-treesitter.ts (markup path) — do not edit by hand.
// Well-formed HTML structure (tags / attributes / text / comments) + raw-text elements.
// Raw-text element bodies (<script>/<style>) are one external `raw_text` token (see
// src/scanner.c), so a literal '<' inside them is content, not markup.
module.exports = grammar({
  name: 'html',
  externals: $ => [$.raw_text],
  extras: $ => [/\s+/],
  rules: {
    document: $ => repeat($._node),
    _node: $ => choice($.element, $.comment, $.text),
    element: $ => choice(
      $.raw_element,
      $.void_element,
      $.self_closing_tag,
      seq($.start_tag, repeat($._node), $.end_tag),
    ),
    raw_element: $ => seq('<', alias($._raw_name, $.tag_name), repeat($.attribute), '>', optional($.raw_text), '</', alias($._raw_name, $.tag_name), '>'),
    start_tag: $ => seq('<', $.tag_name, repeat($.attribute), '>'),
    end_tag: $ => seq('</', $.tag_name, '>'),
    self_closing_tag: $ => seq('<', $.tag_name, repeat($.attribute), '/>'),
    void_element: $ => seq('<', alias($._void_name, $.tag_name), repeat($.attribute), optional('/'), '>'),
    attribute: $ => seq($.attribute_name, optional(seq('=', choice($.quoted_attribute_value, $.attribute_value)))),
    attribute_name: $ => /[a-zA-Z][\w:.\-]*/,
    attribute_value: $ => /[^\s"'<>=`]+/,
    quoted_attribute_value: $ => choice(seq('"', optional(/[^"]+/), '"'), seq("'", optional(/[^']+/), "'")),
    tag_name: $ => /[a-zA-Z][\w:.\-]*/,
    _void_name: $ => token(prec(1, /(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)/i)),
    _raw_name: $ => token(prec(2, /(script|style|textarea|title)/i)),
    text: $ => /[^<]+/,
    comment: $ => token(seq('<!--', /[\s\S]*?/, '-->')),
  }
});
