// Generate a TypeScript `.d.ts`-style source describing the *typed* CST that
// `createParser(grammar).parse()` (gen-parser.ts) produces for THIS grammar.
//
// The runtime CST is generic — `CstNode.rule` and `CstLeaf.tokenType` are both
// `string`. This generator specialises those `string`s into the actual set of
// rule names / token types the grammar can yield, so a consumer gets:
//   * a discriminated union `Node` keyed on the `rule` literal (exhaustive switch)
//   * a `TokenType` union for `CstLeaf.tokenType`
//   * per-rule structural typing of `children` (which child kinds can appear)
//
// Everything is DERIVED from the grammar (CstGrammar) — nothing TypeScript- or
// language-specific is hardcoded, matching the engine's language-agnostic rule.
// Field NAMES are deliberately absent: the grammar has no labels on elements
// (e.g. `[$, '.', Ident]`), so children are typed positionally-by-kind, not as
// named accessors. See the note emitted into the output + the report.

import type { CstGrammar, RuleExpr } from './types.ts';
import { isKeywordLiteral } from './grammar-utils.ts';

// The synthetic leaf/node `tokenType`s the lexer + parser emit in addition to
// the grammar's declared token names. Kept in sync with gen-lexer.ts / gen-parser.ts
// (grep the literal `$...` strings there). `$template` is a *node* rule the parser
// builds for interpolated templates, but it surfaces in `CstChild` positions and
// as a `tokenType` is harmless to include; we also emit a `$template` Node below.
const SYNTHETIC_LEAF_TYPES = [
  '$keyword',        // matchLiteral: keyword-shaped literal
  '$punct',          // matchLiteral: punctuation literal
  '$operator',       // Pratt: infix/prefix/postfix operator leaf
  '$templateHead',   // lexer: template up to first `${`
  '$templateMiddle', // lexer: `}` … `${`
  '$templateTail',   // lexer: `}` … closing backtick
] as const;

// `$template` is the synthetic *node* the parser emits for an interpolated
// template literal (gen-parser.ts parseTemplateExpr).
const SYNTHETIC_TEMPLATE_NODE = '$template';

/** A child element a node can contain: either a Node (by rule) or a Leaf (by token type). */
type ChildKind =
  | { kind: 'node'; rule: string }
  | { kind: 'leaf'; tokenType: string };

/**
 * Generate the typed-CST TypeScript source for `grammar`.
 * Returns a self-contained module string (no imports) suitable for writing to a
 * `.ts`/`.d.ts` file and `import`ing or type-checking.
 */
export function generateAstTypes(grammar: CstGrammar): string {
  // The grammar's template token (if any): a ref to it can yield either a plain
  // leaf of that token type OR a `$template` node (parseTemplateExpr) / a
  // `$templateHead` leaf — mirror gen-parser's matchExpr 'ref' branch.
  const templateTokenNames = new Set(grammar.tokens.filter(t => t.template).map(t => t.name));

  // ── 1. Token-type union ──
  // Declared token names + the synthetic leaf types the engine injects.
  const leafTokenTypes = [
    ...grammar.tokens.map(t => t.name).sort(),
    ...SYNTHETIC_LEAF_TYPES,
  ];

  // ── 2/3. Per-rule child kinds ──
  // For each rule, the set of child element kinds a node of that rule can hold,
  // collapsed across the rule body's structure. The parser flattens quantifiers,
  // `sep`, `alt`, and `group` straight into the parent's `children` array, so a
  // node's children are a *sequence drawn from* this set (not a fixed tuple).
  const childKindsByRule = new Map<string, ChildKind[]>();
  for (const rule of grammar.rules) {
    childKindsByRule.set(rule.name, deriveChildKinds(rule.name, grammar));
  }

  // ── Emit ──
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by src/gen-ast-types.ts — do not edit by hand.');
  lines.push('// Typed CST for the parser output of this grammar.');
  lines.push('//');
  lines.push('// LIMITATION — no named fields: the grammar carries no labels on rule');
  lines.push('// elements (e.g. `[$, \'.\', Ident]` has no field names), so children are');
  lines.push('// typed by *kind* (which Node rules / leaf token types can appear), not as');
  lines.push('// named accessors like `node.name`/`node.value`. Named-field accessors would');
  lines.push('// require adding field labels to the grammar DSL (a future enrichment).');
  lines.push('');

  // Position info (mirrors CstNode/CstLeaf in gen-parser.ts).
  lines.push('export interface CstPos {');
  lines.push('  offset: number;');
  lines.push('  end: number;');
  lines.push('}');
  lines.push('');

  // Token-type union.
  lines.push('/** Every `tokenType` a CstLeaf in this grammar can carry. */');
  lines.push(`export type TokenType =\n${unionBody(leafTokenTypes.map(quote))};`);
  lines.push('');

  // Generic leaf — narrowable on `tokenType`.
  lines.push('/** A terminal: one lexer token (or synthetic keyword/punct/operator leaf). */');
  lines.push('export interface CstLeaf extends CstPos {');
  lines.push('  tokenType: TokenType;');
  lines.push('}');
  lines.push('');

  // The `$template` synthetic node, if the grammar has a template token.
  const hasTemplate = templateTokenNames.size > 0;
  if (hasTemplate) {
    lines.push('/** Synthetic node the parser builds for an interpolated template literal. */');
    lines.push(`export interface ${nodeIfaceName(SYNTHETIC_TEMPLATE_NODE)} extends CstPos {`);
      lines.push(`  rule: ${quote(SYNTHETIC_TEMPLATE_NODE)};`);
    // A $template node holds template leaves plus interpolated expression nodes.
    lines.push('  children: CstChild[];');
    lines.push('}');
    lines.push('');
  }

  // Per-rule interfaces.
  for (const rule of grammar.rules) {
    const kinds = childKindsByRule.get(rule.name)!;
    lines.push(`/** \`${rule.name}\` node. Children (flattened, in source order) are drawn from: */`);
    lines.push(`export interface ${nodeIfaceName(rule.name)} extends CstPos {`);
      lines.push(`  rule: ${quote(rule.name)};`);
    lines.push(`  children: ${childArrayType(kinds)};`);
    lines.push('}');
    lines.push('');
  }

  // Discriminated union of all node interfaces (keyed on `rule`).
  const nodeMembers = [
    ...(hasTemplate ? [nodeIfaceName(SYNTHETIC_TEMPLATE_NODE)] : []),
    ...grammar.rules.map(r => nodeIfaceName(r.name)),
  ];
  lines.push('/** Discriminated union of every node kind. Switch on `node.rule` for exhaustiveness. */');
  lines.push(`export type CstNode =\n${unionBody(nodeMembers)};`);
  lines.push('');

  // The `rule` discriminant as a standalone union (handy for callers).
  const ruleLiterals = [
    ...(hasTemplate ? [SYNTHETIC_TEMPLATE_NODE] : []),
    ...grammar.rules.map(r => r.name),
  ];
  lines.push('/** Every `rule` discriminant value (the keys of the CstNode union). */');
  lines.push(`export type RuleName =\n${unionBody(ruleLiterals.map(quote))};`);
  lines.push('');

  // CstChild.
  lines.push('/** Any CST element: a node or a leaf. */');
  lines.push('export type CstChild = CstNode | CstLeaf;');
  lines.push('');

  // A by-rule lookup type, so callers can write `NodeOf<\'Expr\'>`.
  lines.push('/** Narrow the CstNode union to the node for a given rule name. */');
  lines.push('export type NodeOf<R extends RuleName> = Extract<CstNode, { rule: R }>;');
  lines.push('');

  return lines.join('\n');
}

// ── Child-kind derivation ──

/**
 * The set of child element kinds a node of `ruleName` can directly contain.
 *
 * The parser (gen-parser.ts) flattens `seq`/`alt`/`group`/`quantifier`/`sep`
 * straight into the parent node's `children` array, so we walk the whole body
 * and union every terminal/ref it can reach as a direct child:
 *   - literal           → `$keyword` (keyword-shaped) or `$punct` (punctuation) leaf
 *   - ref → token       → a leaf of that token name (+ `$template`/`$templateHead`
 *                          if it is the template token)
 *   - ref → rule        → that rule's Node
 *   - op/prefix/postfix → handled below for Pratt rules (operator leaves + self-ref)
 *
 * Pratt / left-recursive rules additionally build children the body doesn't show
 * literally — `[lhs, opLeaf, rhs]`, `[opLeaf, rhs]`, `[lhs, opLeaf]` — where `lhs`
 * and `rhs` are nodes of the SAME rule and `opLeaf` is a `$operator` leaf. We add
 * a self Node-ref and `$operator` whenever the body contains an op/prefix/postfix
 * marker, so the type matches what the parser actually emits.
 */
function deriveChildKinds(ruleName: string, grammar: CstGrammar): ChildKind[] {
  const tokenNames = new Set(grammar.tokens.map(t => t.name));
  const ruleNames = new Set(grammar.rules.map(r => r.name));
  const templateTokenNames = new Set(grammar.tokens.filter(t => t.template).map(t => t.name));
  const rule = grammar.rules.find(r => r.name === ruleName)!;

  // De-dup by a stable key.
  const seen = new Map<string, ChildKind>();
  const add = (c: ChildKind) => {
    const key = c.kind === 'node' ? `n:${c.rule}` : `l:${c.tokenType}`;
    if (!seen.has(key)) seen.set(key, c);
  };

  let sawMarker = false;

  function walk(expr: RuleExpr): void {
    switch (expr.type) {
      case 'literal':
        add({ kind: 'leaf', tokenType: isKeywordLiteral(expr.value) ? '$keyword' : '$punct' });
        return;
      case 'ref':
        if (tokenNames.has(expr.name)) {
          add({ kind: 'leaf', tokenType: expr.name });
          // A ref to the template token can instead yield a `$template` node or a
          // `$templateHead` leaf (parser's matchExpr 'ref' → parseTemplateExpr).
          if (templateTokenNames.has(expr.name)) {
            add({ kind: 'node', rule: SYNTHETIC_TEMPLATE_NODE });
            add({ kind: 'leaf', tokenType: '$templateHead' });
          }
        } else if (ruleNames.has(expr.name)) {
          add({ kind: 'node', rule: expr.name });
        }
        return;
      case 'seq':
      case 'alt':
        for (const item of expr.items) walk(item);
        return;
      case 'quantifier':
      case 'group':
        walk(expr.body);
        return;
      case 'sep':
        // `sep(el, ',')` → repeated `el` interleaved with the `,` delimiter leaf.
        walk(expr.element);
        add({ kind: 'leaf', tokenType: isKeywordLiteral(expr.delimiter) ? '$keyword' : '$punct' });
        return;
      case 'op':
      case 'prefix':
      case 'postfix':
        sawMarker = true;
        return;
    }
  }

  walk(rule.body);

  // Pratt synthesis: operator leaves + self node-refs the parser injects.
  if (sawMarker) {
    add({ kind: 'leaf', tokenType: '$operator' });
    add({ kind: 'node', rule: ruleName });
  }

  return [...seen.values()];
}

// ── Emit helpers ──

function nodeIfaceName(ruleName: string): string {
  // `$template` → `$templateNode`; `Expr` → `ExprNode`. The `$` is a legal TS
  // identifier char, so `$templateNode` is a valid interface name.
  return `${ruleName}Node`;
}

/** A single-quoted string literal type, with internal quotes/backslashes escaped. */
function quote(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** Render a list of member type strings as an indented `| a | b | c` union body. */
function unionBody(members: string[]): string {
  if (members.length === 0) return '  never';
  return members.map(m => `  | ${m}`).join('\n');
}

/** The `children` array type for a set of child kinds. */
function childArrayType(kinds: ChildKind[]): string {
  if (kinds.length === 0) {
    // No derivable children (e.g. an empty/marker-only body) — still an array.
    return 'CstChild[]';
  }
  const members = kinds.map(k =>
    k.kind === 'node' ? nodeIfaceName(k.rule) : leafOf(k.tokenType),
  );
  // Sort for stable output; nodes and leaves intermixed is fine.
  members.sort();
  return `Array<\n${members.map(m => `    | ${m}`).join('\n')}\n  >`;
}

/** A `CstLeaf` narrowed to a specific tokenType. */
function leafOf(tokenType: string): string {
  return `(CstLeaf & { tokenType: ${quote(tokenType)} })`;
}
