// The TypeScript Target for emit-portable. Renders the language-agnostic ParserIR into a
// self-contained TS parser: a char-class lexer, a backtracking recursive-descent core, a
// Pratt expression engine, and a CST→JSON printer over stdin. It is the reference rendering
// — its CST is checked byte-for-byte against the interpreter (createParser), so a divergence
// in the portable logic shows up here before Go/Rust are even compiled.
import type { ParserIR, RdRule, PrattRule, Step, CharRange, Target } from './emit-portable.ts';

const J = (v: unknown) => JSON.stringify(v);
const rangeCond = (v: string, rs: CharRange[]) =>
  rs.map(([lo, hi]) => (lo === hi ? `${v} === ${lo}` : `${v} >= ${lo} && ${v} <= ${hi}`)).join(' || ');

function lexer(ir: ParserIR): string {
  const cases = ir.tokens.map((t) => `    if (${rangeCond('c', t.first)}) {
      let e = pos + 1;
      while (e < n) { const cc = src.charCodeAt(e); if (!(${rangeCond('cc', t.cont)})) break; e++; }
      toks.push({ kind: ${J(t.name)}, text: src.slice(pos, e), off: pos, end: e }); pos = e; continue;
    }`).join('\n');
  const punctChecks = ir.puncts.map((p) =>
    `    if (src.startsWith(${J(p)}, pos)) { toks.push({ kind: '', text: ${J(p)}, off: pos, end: pos + ${p.length} }); pos += ${p.length}; continue; }`).join('\n');
  return `function lex(src: string): Tok[] {
  const toks: Tok[] = [];
  const n = src.length;
  let pos = 0;
  while (pos < n) {
    const c = src.charCodeAt(pos);
    if (c === 32 || c === 9 || c === 10 || c === 13) { pos++; continue; }
${cases}
${punctChecks}
    throw new Error('lex error at ' + pos + ': ' + JSON.stringify(src[pos]));
  }
  return toks;
}`;
}

function rdRule(r: RdRule): string {
  const alt = (steps: Step[]) => {
    const conds = steps.map(stepCond).join(' && ');
    return `  { const kids: Cst[] = []; if (${conds}) return branch(${J(r.name)}, kids, save); pos = save; }`;
  };
  return `function parse${r.name}(): Node | null {
  const save = pos;
${r.alts.map(alt).join('\n')}
  return null;
}`;
}
function stepCond(s: Step): string {
  switch (s.t) {
    case 'lit': return `matchLit(${J(s.value)}, ${J(s.ttype)}, kids)`;
    case 'tok': return `matchTok(${J(s.name)}, kids)`;
    case 'rule': return `callRule(parse${s.name}, kids)`;
    case 'star': return `star(() => ${stepCond(s.step)}, kids)`;
  }
}

function prattRule(r: PrattRule): string {
  const BIN = `{ ${r.binary.map((b) => `${J(b.op)}: { lbp: ${b.lbp}, rbp: ${b.rbp} }`).join(', ')} }`;
  const PRE = `{ ${r.prefix.map((p) => `${J(p.op)}: ${p.rbp}`).join(', ')} }`;
  const atomSet = `new Set([${r.atomToks.map(J).join(', ')}])`;
  const group = r.group;
  return `const ${r.name}_BIN: Record<string, { lbp: number; rbp: number }> = ${BIN};
const ${r.name}_PRE: Record<string, number> = ${PRE};
const ${r.name}_ATOM = ${atomSet};
function parse${r.name}(): Node | null { return ${r.name}_bp(0); }
function ${r.name}_bp(minBp: number): Node | null {
  let left = ${r.name}_nud();
  if (left === null) return null;
  for (;;) {
    const t = peek();
    if (t === null) break;
    const info = ${r.name}_BIN[t.text];
    if (info === undefined || info.lbp <= minBp) break;
    const ledSave = pos;
    pos++;
    const opLeaf: Leaf = { tokenType: '$operator', offset: t.off, end: t.end };
    const rhs = ${r.name}_bp(info.rbp);
    if (rhs === null) { pos = ledSave; break; }
    left = { rule: ${J(r.name)}, children: [left, opLeaf, rhs], offset: left.offset, end: rhs.end };
  }
  return left;
}
function ${r.name}_nud(): Node | null {
  const t = peek();
  if (t === null) return null;
  if (${r.name}_ATOM.has(t.kind)) { pos++; return { rule: ${J(r.name)}, children: [{ tokenType: t.kind, offset: t.off, end: t.end }], offset: t.off, end: t.end }; }
${group ? `  if (t.text === ${J(group.open)}) {
    const save = pos; pos++;
    const inner = ${r.name}_bp(0);
    const c = peek();
    if (inner === null || c === null || c.text !== ${J(group.close)}) { pos = save; return null; }
    pos++;
    return { rule: ${J(r.name)}, children: [{ tokenType: '$punct', offset: t.off, end: t.end }, inner, { tokenType: '$punct', offset: c.off, end: c.end }], offset: t.off, end: c.end };
  }` : ''}
  const pbp = ${r.name}_PRE[t.text];
  if (pbp !== undefined) {
    const save = pos; pos++;
    const opLeaf: Leaf = { tokenType: '$operator', offset: t.off, end: t.end };
    const operand = ${r.name}_bp(pbp);
    if (operand === null) { pos = save; return null; }
    return { rule: ${J(r.name)}, children: [opLeaf, operand], offset: t.off, end: operand.end };
  }
  return null;
}`;
}

export const tsTarget: Target = {
  name: 'typescript',
  ext: 'ts',
  render(ir: ParserIR): string {
    const ruleFns = ir.rules.map((r) => (r.kind === 'pratt' ? prattRule(r) : rdRule(r))).join('\n\n');
    return `// GENERATED by emit-portable.ts (tsTarget) — parser for grammar "${ir.grammarName}".
import { readFileSync } from 'node:fs';

type Tok = { kind: string; text: string; off: number; end: number };
type Leaf = { tokenType: string; offset: number; end: number };
type Node = { rule: string; children: Cst[]; offset: number; end: number };
type Cst = Node | Leaf;

${lexer(ir)}

let toks: Tok[] = [];
let pos = 0;
function peek(): Tok | null { return pos < toks.length ? toks[pos] : null; }
function curOff(): number { return pos < toks.length ? toks[pos].off : (toks.length > 0 ? toks[toks.length - 1].end : 0); }
function branch(rule: string, kids: Cst[], save: number): Node {
  const offset = kids.length > 0 ? kids[0].offset : (save < toks.length ? toks[save].off : curOff());
  const end = kids.length > 0 ? kids[kids.length - 1].end : offset;
  return { rule, children: kids, offset, end };
}
function matchLit(value: string, ttype: string, kids: Cst[]): boolean {
  const t = peek();
  if (t === null || t.text !== value) return false;
  kids.push({ tokenType: ttype, offset: t.off, end: t.end }); pos++; return true;
}
function matchTok(name: string, kids: Cst[]): boolean {
  const t = peek();
  if (t === null || t.kind !== name) return false;
  kids.push({ tokenType: name, offset: t.off, end: t.end }); pos++; return true;
}
function callRule(fn: () => Node | null, kids: Cst[]): boolean {
  const n = fn();
  if (n === null) return false;
  kids.push(n); return true;
}
function star(once: () => boolean, kids: Cst[]): boolean {
  for (;;) { const sp = pos; const before = kids.length; if (!once()) { pos = sp; kids.length = before; break; } }
  return true;
}

${ruleFns}

function offsetEnd(n: Cst): number { return n.end; }
const src = readFileSync(0, 'utf8');
toks = lex(src);
pos = 0;
const root = parse${ir.entry}();
if (root === null || pos !== toks.length) {
  process.stderr.write('parse error (pos ' + pos + '/' + toks.length + ')\\n');
  process.exit(1);
}
process.stdout.write(JSON.stringify(root));
`;
  },
};
