// The Go Target for emit-portable. Renders the same language-agnostic ParserIR as tsTarget
// into a self-contained Go program (Go stdlib only — the char-class lexer is regex-free, so
// it compiles with no module dependencies). Its CST JSON is checked byte-for-byte against
// the interpreter, so `emitPortableParser(grammar, goTarget)` is a real, verified Go parser
// derived from the same grammar definition.
import type { ParserIR, RdRule, PrattRule, Step, CharRange, Target } from './emit-portable.ts';

const J = (v: unknown) => JSON.stringify(v);
const goStr = (s: string) => J(s);   // Go and JSON string literals coincide for our ASCII vocab
const rangeCond = (v: string, rs: CharRange[]) =>
  rs.map(([lo, hi]) => (lo === hi ? `${v} == ${lo}` : `${v} >= ${lo} && ${v} <= ${hi}`)).join(' || ');

function lexer(ir: ParserIR): string {
  const cases = ir.tokens.map((t) => `\t\tif ${rangeCond('c', t.first)} {
\t\t\te := pos + 1
\t\t\tfor e < n { cc := int(src[e]); if !(${rangeCond('cc', t.cont)}) { break }; e++ }
\t\t\ttoks = append(toks, Tok{${goStr(t.name)}, src[pos:e], pos, e}); pos = e; continue
\t\t}`).join('\n');
  const punctChecks = ir.puncts.map((p) =>
    `\t\tif strings.HasPrefix(src[pos:], ${goStr(p)}) { toks = append(toks, Tok{"", ${goStr(p)}, pos, pos + ${p.length}}); pos += ${p.length}; continue }`).join('\n');
  return `func lex(src string) []Tok {
\ttoks := []Tok{}
\tn := len(src)
\tpos := 0
\tfor pos < n {
\t\tc := int(src[pos])
\t\tif c == 32 || c == 9 || c == 10 || c == 13 { pos++; continue }
${cases}
${punctChecks}
\t\tpanic(fmt.Sprintf("lex error at %d", pos))
\t}
\treturn toks
}`;
}

function rdRule(r: RdRule): string {
  const alt = (steps: Step[]) => {
    const conds = steps.map(stepCond).join(' && ');
    return `\t{ kids := []*Cst{}; if ${conds} { return branch(${goStr(r.name)}, kids, save) }; pos = save }`;
  };
  return `func parse${r.name}() *Cst {
\tsave := pos
${r.alts.map(alt).join('\n')}
\treturn nil
}`;
}
function stepCond(s: Step): string {
  switch (s.t) {
    case 'lit': return `matchLit(${goStr(s.value)}, ${goStr(s.ttype)}, &kids)`;
    case 'tok': return `matchTok(${goStr(s.name)}, &kids)`;
    case 'rule': return `callRule(parse${s.name}, &kids)`;
    case 'star': return `star(func() bool { return ${stepCond(s.step)} }, &kids)`;
  }
}

function prattRule(r: PrattRule): string {
  const bin = r.binary.map((b) => `${goStr(b.op)}: {${b.lbp}, ${b.rbp}}`).join(', ');
  const pre = r.prefix.map((p) => `${goStr(p.op)}: ${p.rbp}`).join(', ');
  const atoms = r.atomToks.map((k) => `${goStr(k)}: true`).join(', ');
  const g = r.group;
  return `var ${r.name}BIN = map[string]bp{${bin}}
var ${r.name}PRE = map[string]int{${pre}}
var ${r.name}ATOM = map[string]bool{${atoms}}
func parse${r.name}() *Cst { return ${r.name}bp(0) }
func ${r.name}bp(minBp int) *Cst {
\tleft := ${r.name}nud()
\tif left == nil { return nil }
\tfor {
\t\tt := peek()
\t\tif t == nil { break }
\t\tinfo, ok := ${r.name}BIN[t.Text]
\t\tif !ok || info.lbp <= minBp { break }
\t\tledSave := pos
\t\tpos++
\t\topLeaf := &Cst{IsLeaf: true, TokenType: "$operator", Offset: t.Off, End: t.End}
\t\trhs := ${r.name}bp(info.rbp)
\t\tif rhs == nil { pos = ledSave; break }
\t\tleft = &Cst{Rule: ${goStr(r.name)}, Children: []*Cst{left, opLeaf, rhs}, Offset: left.Offset, End: rhs.End}
\t}
\treturn left
}
func ${r.name}nud() *Cst {
\tt := peek()
\tif t == nil { return nil }
\tif ${r.name}ATOM[t.Kind] {
\t\tpos++
\t\treturn &Cst{Rule: ${goStr(r.name)}, Children: []*Cst{{IsLeaf: true, TokenType: t.Kind, Offset: t.Off, End: t.End}}, Offset: t.Off, End: t.End}
\t}
${g ? `\tif t.Text == ${goStr(g.open)} {
\t\tsave := pos; pos++
\t\tinner := ${r.name}bp(0)
\t\tc := peek()
\t\tif inner == nil || c == nil || c.Text != ${goStr(g.close)} { pos = save; return nil }
\t\tpos++
\t\treturn &Cst{Rule: ${goStr(r.name)}, Children: []*Cst{{IsLeaf: true, TokenType: "$punct", Offset: t.Off, End: t.End}, inner, {IsLeaf: true, TokenType: "$punct", Offset: c.Off, End: c.End}}, Offset: t.Off, End: c.End}
\t}` : ''}
\tif pbp, ok := ${r.name}PRE[t.Text]; ok {
\t\tsave := pos; pos++
\t\topLeaf := &Cst{IsLeaf: true, TokenType: "$operator", Offset: t.Off, End: t.End}
\t\toperand := ${r.name}bp(pbp)
\t\tif operand == nil { pos = save; return nil }
\t\treturn &Cst{Rule: ${goStr(r.name)}, Children: []*Cst{opLeaf, operand}, Offset: t.Off, End: operand.End}
\t}
\treturn nil
}`;
}

export const goTarget: Target = {
  name: 'go',
  ext: 'go',
  render(ir: ParserIR): string {
    const ruleFns = ir.rules.map((r) => (r.kind === 'pratt' ? prattRule(r) : rdRule(r))).join('\n\n');
    return `// GENERATED by emit-portable.ts (goTarget) — parser for grammar "${ir.grammarName}".
package main

import (
\t"fmt"
\t"io"
\t"os"
\t"strings"
)

type Tok struct {
\tKind, Text string
\tOff, End   int
}
type Cst struct {
\tRule      string
\tChildren  []*Cst
\tIsLeaf    bool
\tTokenType string
\tOffset    int
\tEnd       int
}
type bp struct{ lbp, rbp int }

${lexer(ir)}

var toks []Tok
var pos int

func peek() *Tok {
\tif pos < len(toks) { return &toks[pos] }
\treturn nil
}
func branch(rule string, kids []*Cst, save int) *Cst {
\toffset := 0
\tif len(kids) > 0 { offset = kids[0].Offset } else if save < len(toks) { offset = toks[save].Off } else if len(toks) > 0 { offset = toks[len(toks)-1].End }
\tend := offset
\tif len(kids) > 0 { end = kids[len(kids)-1].End }
\treturn &Cst{Rule: rule, Children: kids, Offset: offset, End: end}
}
func matchLit(value, ttype string, kids *[]*Cst) bool {
\tt := peek()
\tif t == nil || t.Text != value { return false }
\t*kids = append(*kids, &Cst{IsLeaf: true, TokenType: ttype, Offset: t.Off, End: t.End}); pos++; return true
}
func matchTok(name string, kids *[]*Cst) bool {
\tt := peek()
\tif t == nil || t.Kind != name { return false }
\t*kids = append(*kids, &Cst{IsLeaf: true, TokenType: name, Offset: t.Off, End: t.End}); pos++; return true
}
func callRule(fn func() *Cst, kids *[]*Cst) bool {
\tn := fn()
\tif n == nil { return false }
\t*kids = append(*kids, n); return true
}
func star(once func() bool, kids *[]*Cst) bool {
\tfor { sp := pos; before := len(*kids); if !once() { pos = sp; *kids = (*kids)[:before]; break } }
\treturn true
}

${ruleFns}

func writeJSON(c *Cst, b *strings.Builder) {
\tif c.IsLeaf {
\t\tfmt.Fprintf(b, "{\\"tokenType\\":%q,\\"offset\\":%d,\\"end\\":%d}", c.TokenType, c.Offset, c.End)
\t\treturn
\t}
\tfmt.Fprintf(b, "{\\"rule\\":%q,\\"children\\":[", c.Rule)
\tfor i, k := range c.Children {
\t\tif i > 0 { b.WriteByte(',') }
\t\twriteJSON(k, b)
\t}
\tfmt.Fprintf(b, "],\\"offset\\":%d,\\"end\\":%d}", c.Offset, c.End)
}

func main() {
\tdata, _ := io.ReadAll(os.Stdin)
\ttoks = lex(string(data))
\tpos = 0
\troot := parse${ir.entry}()
\tif root == nil || pos != len(toks) {
\t\tfmt.Fprintf(os.Stderr, "parse error (pos %d/%d)\\n", pos, len(toks))
\t\tos.Exit(1)
\t}
\tvar b strings.Builder
\twriteJSON(root, &b)
\tos.Stdout.WriteString(b.String())
}
`;
  },
};
