// AUTO-GENERATED by src/gen-treesitter.ts (markup path) — do not edit by hand.
// Tree-sitter external scanner for raw-text element bodies (<script>/<style>/…).
// No libc: the wasm toolchain doesn't link <ctype.h>/<string.h> (their symbols become
// unresolved imports), so the ASCII helpers below are inlined.
#include "tree_sitter/parser.h"

enum TokenType { RAW_TEXT };

// Raw-text tag names — DERIVED from the grammar's markup.rawText.tags.
static const char *RAW_TAGS[] = { "template", "script", "style" };
static const unsigned RAW_TAG_COUNT = 3;

static int ascii_alpha(int ch) { return (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z'); }
static int ascii_lower(int ch) { return (ch >= 'A' && ch <= 'Z') ? ch + 32 : ch; }
static int name_eq(const char *a, const char *b) { while (*a && *b) { if (*a != *b) return 0; a++; b++; } return *a == *b; }

void *tree_sitter_vue_external_scanner_create(void) { return 0; }
void tree_sitter_vue_external_scanner_destroy(void *p) { (void)p; }
unsigned tree_sitter_vue_external_scanner_serialize(void *p, char *b) { (void)p; (void)b; return 0; }
void tree_sitter_vue_external_scanner_deserialize(void *p, const char *b, unsigned n) { (void)p; (void)b; (void)n; }

// Scan the verbatim body of a raw-text element. A '<' is content unless it begins the
// matching close tag '</name>' (name ∈ RAW_TAGS). We advance past a candidate '</name'
// to test it, but mark the token end BEFORE the '<', so the close tag is left to the
// parser. Returns false on an empty body (immediately a close tag) — the body is optional.
bool tree_sitter_vue_external_scanner_scan(void *payload, TSLexer *lexer, const bool *valid_symbols) {
  (void)payload;
  if (!valid_symbols[RAW_TEXT]) return false;
  lexer->result_symbol = RAW_TEXT;
  bool advanced = false;
  while (!lexer->eof(lexer)) {
    if (lexer->lookahead == '<') {
      lexer->mark_end(lexer);            // body ends here if this is the close tag
      lexer->advance(lexer, false);      // consume '<'
      if (lexer->lookahead == '/') {
        lexer->advance(lexer, false);    // consume '/'
        char name[16];
        unsigned n = 0;
        while (n < 15 && ascii_alpha((int)lexer->lookahead)) {
          name[n++] = (char)ascii_lower((int)lexer->lookahead);
          lexer->advance(lexer, false);
        }
        name[n] = '\0';
        for (unsigned i = 0; i < RAW_TAG_COUNT; i++) {
          if (name_eq(name, RAW_TAGS[i])) return advanced;  // close tag → stop (end marked before '<')
        }
        advanced = true;                 // '</xxx' was body content; keep scanning
        continue;
      }
      advanced = true;                   // a lone '<' is body content
      continue;
    }
    lexer->advance(lexer, false);
    advanced = true;
  }
  lexer->mark_end(lexer);                 // EOF: the whole remainder is the body
  return advanced;
}
