// External tokenizer for javascript (generated by gen-lezer.ts).
//
// Lezer external tokenizers are plain JS, so we implement the context-sensitive
// lexing that the grammar's token HINTS describe — the same logic gen-lexer.ts
// uses — more fully than a Lezer-native C scanner could. Wire the exported
// tokenizers into the .grammar via:
//
//   @external tokens contextTokens from "./tokens.js" { Regex, Template, TemplateHead, TemplateMiddle, TemplateTail }
//
// This module must also supply these tokens that exceeded Lezer's @tokens syntax
// (straightforward longest-match scanners — INCOMPLETE, regex listed for porting):
//   JSDoc: /\/\*\*(?!\/)[\s\S]*?\*\//  (skip)
//   BlockComment: /\/\*[\s\S]*?\*\//  (skip)
//   Ident: /(?:[a-zA-Z_$]|\\u[0-9a-fA-F]{4}|\\u\{[0-9a-fA-F]+\})(?:[a-zA-Z0-9_$]|\\u[0-9a-fA-F]{4}|\\u\{[0-9a-fA-F]+\})*/
//   HexNumber: /0[xX][0-9a-fA-F]+(_[0-9a-fA-F]+)*(?![0-9A-Za-z_$\\])/
//   OctalNumber: /0[oO][0-7]+(_[0-7]+)*(?![0-9A-Za-z_$\\])/
//   BinaryNumber: /0[bB][01]+(_[01]+)*(?![0-9A-Za-z_$\\])/
//   BigInt: /[0-9]+(_[0-9]+)*n(?![0-9A-Za-z_$\\])/
//   Number: /[0-9]+(_[0-9]+)*(?:\.[0-9]*(_[0-9]+)*)?(?:[eE][+-]?[0-9]+(_[0-9]+)*)?(?![0-9A-Za-z_$\\])/
//   String: /"(?:[^"\\]|\\(?:u\{0*(?:[0-9a-fA-F]{1,5}|10[0-9a-fA-F]{4})\}|u[0-9a-fA-F]{4}|x[0-9a-fA-F]{2}|[^ux]))*"|'(?:[^'\\]|\\(?:u\{0*(?:[0-9a-fA-F]{1,5}|10[0-9a-fA-F]{4})\}|u[0-9a-fA-F]{4}|x[0-9a-fA-F]{2}|[^ux]))*'/
//   Decorator: /@(?:[a-zA-Z_$][a-zA-Z0-9_$.]*)?/
//
// NOTE: `@lezer/generator` passes the matching term ids in; the names below must
// match the @external tokens { ... } list. Replace the term imports accordingly.

import { ExternalTokenizer } from "@lezer/lr";
// import { Regex, Template, TemplateHead, TemplateMiddle, TemplateTail } from "./parser.terms.js";

// Characters/texts after which `/` is DIVISION (value-producing), not a regex.
const divisionAfterTexts = [")","]","++","--","this","super","true","false","null","undefined"];
// Keywords that re-enter expression position, so `/` after them IS a regex.
const regexAfterTexts = ["in","of","instanceof","typeof","delete","void","await","yield","throw","return","case","do","else","new"];

// The JS regex for a regex literal (from the grammar's @regex token).
// Built via RegExp(source) so the pattern's own \/ escapes survive verbatim
// (embedding in a /.../ literal would double-escape them). 'y' = sticky.
const REGEX_LITERAL = new RegExp("\\/(?:[^\\/\\\\\\[\\n]|\\\\.|\\[(?:[^\\]\\\\\\n]|\\\\.)*\\])+\\/[gimsuydv]*", "y");

const IDENT_CHAR = /[\p{L}\p{Nl}\p{Nd}\p{Mn}\p{Mc}\p{Pc}_$]/u;

/**
 * Regex-vs-division tokenizer. Lezer calls this where a `Regex` token is valid.
 * We decide using the PREVIOUS significant token's text/type, mirroring
 * gen-lexer.ts's `divisionPrevTexts`/`expressionStartKeywords` logic.
 *
 * INCOMPLETE: Lezer's `InputStream` does not expose the previous token's TYPE,
 * only characters. We approximate the "division after a value" rule by scanning
 * backwards over whitespace to the previous non-space char and checking the
 * divisionAfterTexts set. Token-TYPE-sensitive cases (Ident/Number/String/…)
 * are handled by Lezer's own tokens taking priority; this hook only fires the
 * regex when a `/` is genuinely in expression position.
 */
export const contextTokens = new ExternalTokenizer((input, stack) => {
  const next = input.next;
  if (next !== 47 /* '/' */) return;

  // Look back at the previous non-whitespace char already consumed.
  let back = -1;
  let prev = input.peek(back);
  while (prev === 32 || prev === 9 || prev === 10 || prev === 13) { back--; prev = input.peek(back); }

  if (prev >= 0) {
    const prevChar = String.fromCharCode(prev);
    // After a closing bracket / identifier char / digit → division, not regex.
    if (prevChar === ")" || prevChar === "]" || prevChar === "}") return;
    if (/[A-Za-z0-9_$]/.test(prevChar)) {
      // Could be an identifier OR an expression-start keyword (return, typeof, …).
      // Read the whole preceding word and consult regexAfterTexts.
      let w = "", b = back;
      let ch = input.peek(b);
      while (ch >= 0 && /[A-Za-z0-9_$]/.test(String.fromCharCode(ch))) { w = String.fromCharCode(ch) + w; b--; ch = input.peek(b); }
      if (!regexAfterTexts.includes(w)) return;   // a plain identifier → division
      // else: keyword like `return` → fall through and match a regex literal
    }
  }

  // Try to match a regex literal at the current position.
  REGEX_LITERAL.lastIndex = 0;
  let s = "";
  // Re-read from the input stream char-by-char to feed the sticky regex.
  // (InputStream is forward-only; accumulate then test.)
  let i = 0, c = input.peek(i);
  // Bound the scan to a single line to avoid runaway on malformed input.
  while (c >= 0 && c !== 10 && i < 5000) { s += String.fromCharCode(c); i++; c = input.peek(i); }
  const m = REGEX_LITERAL.exec(s);
  if (m && m.index === 0) {
    input.advance(m[0].length);
    input.acceptToken(/* Regex */ 1);
  }
});

// ── Template-literal tokenizer ──
// Splits an interpolated template into Head / Middle / Tail around `${…}`
// holes, matching gen-lexer.ts's scanTemplateSpan. Delimiters come from the
// grammar's template token hint (language-agnostic).
const TPL_OPEN = "`";
const TPL_INTERP_OPEN = "${";
const TPL_INTERP_CLOSE = "}";

/**
 * INCOMPLETE: a production template tokenizer must track interpolation-brace
 * nesting depth across tokenizer invocations (Lezer re-enters per token). The
 * scaffold below tokenizes a non-interpolated template fully and emits a
 * Head token up to the first interpolation; the Middle/Tail transitions need a
 * small stack threaded through the parser's context (`stack`). Mark and finish
 * when wiring into a concrete @lezer/lr build.
 */
export const templateTokens = new ExternalTokenizer((input, stack) => {
  let i = 0;
  // expect the opening delimiter
  for (let k = 0; k < TPL_OPEN.length; k++) {
    if (input.peek(i) !== TPL_OPEN.charCodeAt(k)) return;
    i++;
  }
  // scan to closing delimiter or interpolation hole
  while (true) {
    const c = input.peek(i);
    if (c < 0) return;                          // unterminated
    if (c === 92 /* \\ */) { i += 2; continue; }
    if (startsWith(input, i, TPL_INTERP_OPEN)) {
      input.advance(i + TPL_INTERP_OPEN.length);
      input.acceptToken(/* TemplateHead */ 2);  // INCOMPLETE: distinguish Head vs Middle via stack
      return;
    }
    if (startsWith(input, i, TPL_OPEN)) {
      input.advance(i + TPL_OPEN.length);
      input.acceptToken(/* Template */ 3);
      return;
    }
    i++;
  }
});

function startsWith(input, at, s) {
  for (let k = 0; k < s.length; k++) {
    if (input.peek(at + k) !== s.charCodeAt(k)) return false;
  }
  return true;
}
